### PR TITLE
✨ Improve the snapshot script

### LINKED ISSUE #2783: bug: Another crash of the snapshot script
### Describe the bug

I was testing with the following loop, and the demo env creation script failed, and then the snapshot script failed.

```shell
while time bash <(curl -s https://raw.githubusercontent.com/kubestellar/kubestellar/refs/heads/main/scripts/create-kubestellar-demo-env.sh); do
    date
    sleep 1
done; date; bash <(curl -s https://raw.githubusercontent.com/kubestellar/kubestellar/refs/heads/main/scripts/kubestellar-snapshot.sh) -V -Y -L
```

Following is the tail of the log.

```console
...
Finally, you can use `kflex ctx` to switch back to the kubeconfig
context for your KubeFlex hosting cluster.
✔ Checking for saved hosting cluster context...
✔ Switching to hosting cluster context...
trying to load new context wds1 from server...
✔ Overwriting existing context for control plane
◒ Switching to context wds1...Error loading and merging kubeconfig: error waiting for control plane kubeconfig secret: context deadline exceeded, client rate limiter Wait returned an error: context deadline exceeded
bash   5.59s user 8.29s system 0% cpu 1:50:52.02 total
Tue Feb  4 06:30:53 EST 2025
KubeStellar Snapshot v0.2.0{COLOR_NONE}

Script run on 2025-02-04_06:30:53
Checking script dependencies:
✔ kubectl version v1.29.2 at /Users/mspreitz/.rd/bin/kubectl
✔ helm version v3.16.1 at /Users/mspreitz/.rd/bin/helm
✔ jq version jq-1.6-159-apple-gcff5336-dirty at /usr/bin/jq
Using kubeconfig(s): /Users/mspreitz/.kube/config
Validating contexts(s): 
X /api-prod-dipc-res-ibm-com:6443/4A5349897@W3IDRealm 
✔ cluster1 
✔ cluster2 
X default/api-epoc2e-ete14-res-ibm-com:6443/kube:admin 
X default/c106-e-us-south-containers-cloud-ibm-com:31891/IAM#mspreitz@us.ibm.com 
X default/c114-e-us-south-containers-cloud-ibm-com:30301/IAM#mspreitz@us.ibm.com 
X default/c114-e-us-south-containers-cloud-ibm-com:31314/IAM#mspreitz@us.ibm.com 
X default/c117-e-us-south-containers-cloud-ibm-com:31786/IAM#mspreitz@us.ibm.com 
X its1 
✔ kind-kubeflex *
X ks-edge-cluster1 
X ks-edge-cluster2 
X rancher-desktop 
X test-its1 
X test-wds1 
X wec1 
X wec2 

KubeStellar:
- Helm chart ks-core (v0.26.0-rc.1) in namespace default in context kind-kubeflex
  - Secret=sh.helm.release.v1.ks-core.v1 in namespace default

KubeFlex:
- kubeflex-system namespace in context kind-kubeflex
- controller-manager: version=0.8.0, pod=kubeflex-controller-manager-7f979c4df6-lkctw, status=running
- postgres-postgresql-0: pod=postgres-postgresql-0, status=running

Control Planes:
- its1: type=vcluster, pch=its-with-clusteradm, context=kind-kubeflex, namespace=its1-system
  WARNING: the Control Plane is not ready, the kubeconfig is not available!
  - Post Create Hook: pod=, ns=its1-system, status=
  - Status addon controller: pod=, ns=its1-system, version=, status=
error: expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.
POD or TYPE/NAME is a required argument for the logs command
See 'kubectl logs -h' for help and examples
```

### Output from KubeStellar-Snapshot.sh

Included above.

### Steps To Reproduce

Shown above.

### Expected Behavior

No sign of failure in the raptuous snapshot script.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

Issue #2724 also concerns fragility of this script.

### PR DESCRIPTION
**Pull request by francostellari**
## Summary
- move the creation of the tar file to a trap function to make sure that it is saved even on error
- do not exit after missing postgresql error
- check the presence/absence of KubeFlex, KubeStellar, and OCM CRDs

## Related issue(s)
- #2786: do not exit after missing postgresql error

Fixes #2783

### CODE REVIEW

File: scripts/kubestellar-snapshot.sh [hunk 1]
```diff
@@ -217,7 +233,7 @@ fi
 ###############################################################################
 # Script info
 ###############################################################################
-echov -e "${COLOR_INFO}${SCRIPT_NAME} v${SCRIPT_VERSION}{COLOR_NONE}\n"
+echov -e "${COLOR_INFO}${SCRIPT_NAME} v${SCRIPT_VERSION}${COLOR_NONE}\n"
```
Comment (MikeSpreitzer) [inline scripts/kubestellar-snapshot.sh:236]: Yeah, this too.

File: scripts/kubestellar-snapshot.sh [hunk 2]
```diff
@@ -349,15 +365,30 @@ else
         postgresql_pod=$(kubectl --context $helm_context -n kubeflex-system get pod postgres-postgresql-0 2> /dev/null || true)
         if [ -z "$postgresql_pod" ]; then
             echoerr "postgres-postgresql-0 pod not found!"
+            postgresql_job=$(kubectl --context $helm_context -n kubeflex-system get pod --no-headers -o name | grep "install-postgres" | head -n 2> /dev/null || true)
```
Comment (MikeSpreitzer) [inline scripts/kubestellar-snapshot.sh:368]: `head -n` ?? how many?

File: scripts/kubestellar-snapshot.sh [hunk 3]
```diff
@@ -349,15 +365,30 @@ else
...
+            if [ -n "$postgresql_job" ]; then
+                echo -e "Found at least one ${COLOR_INFO}postgresql${COLOR_NONE} installation job that did not complete: ${COLOR_INFO}$postgresql_job${COLOR_NONE}"
```
Comment (MikeSpreitzer) [inline scripts/kubestellar-snapshot.sh:370]: (A) Wouldn't it be more clear for the English words here to speak of a Pod, since that is what's being listed?

(B) Is there a `pod/` prefix to strip from the `-o name` output?

File: scripts/kubestellar-snapshot.sh [hunk 4]
```diff
@@ -349,15 +365,30 @@ else
...
+                if kubectl --context $helm_context -n kubeflex-system logs $postgresql_job | grep "toomanyrequests" ; then
+                    echoerr "there may be an issue pulling the postgresql image from Docker Hub."
```
Comment (MikeSpreitzer) [inline scripts/kubestellar-snapshot.sh:372]: Just saying "there may be an issue with..." gives the user less information that we have. Wouldn't it be better to exhibit the actual error message or whole log?

File: scripts/kubestellar-snapshot.sh [hunk 5]
```diff
@@ -349,15 +365,30 @@ else
...
+                fi
+            fi
         else
             postgresql_status=$(kubectl --context $helm_context -n kubeflex-system get pod postgres-postgresql-0 -o jsonpath='{.status.phase}' 2> /dev/null || true)
             echo -n -e "- ${COLOR_INFO}postgres-postgresql-0${COLOR_NONE}: pod=${COLOR_INFO}postgres-postgresql-0${COLOR_NONE}, status="
             echostatus "$postgresql_status"
         fi
+        for crd in controlplanes.tenancy.kflex.kubestellar.org postcreatehooks.tenancy.kflex.kubestellar.org ; do
+            echo -n -e "- CRD ${COLOR_INFO}$crd${COLOR_NONE} "
+            if [ -n "$(kubectl --context $helm_context get crd $crd --no-headers -o name 2> /dev/null || true)" ] ; then
```
Comment (MikeSpreitzer) [inline scripts/kubestellar-snapshot.sh:382]: Wouldn't it be simpler to do the following instead?

```suggestion
            if kubectl --context $helm_context get crd $crd &> /dev/null; then
```

File: scripts/kubestellar-snapshot.sh [hunk 6]
```diff
@@ -408,6 +439,14 @@ for i in "${!cps[@]}" ; do # for all control planes in context ${context}
                 echo -e "  - Open-cluster-manager: ${COLOR_ERROR}not found${COLOR_NONE}"
             fi
         fi
+        for crd in workstatuses.control.kubestellar.io  clustermanagers.operator.open-cluster-management.io clustermanagementaddons.addon.open-cluster-management.io managedclusters.cluster.open-cluster-management.io managedclustersets.cluster.open-cluster-management.io manifestworks.work.open-cluster-management.io manifestworkreplicasets.work.open-cluster-management.io  managedclusteraddons.addon.open-cluster-management.io  managedclustersetbindings.cluster.open-cluster-management.io placements.cluster.open-cluster-management.io addondeploymentconfigs.addon.open-cluster-management.io addontemplates.addon.open-cluster-management.io placementdecisions.cluster.open-cluster-management.io addonplacementscores.cluster.open-cluster-management.io ; do
```
[the remark this answers is not in the document]
Comment (francostellari) [reply scripts/kubestellar-snapshot.sh:442]: Do you mean to report a list of the CRDs that are present rather than check if specific ones are present?

[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply scripts/kubestellar-snapshot.sh:442]: yes, but not all. Just the ones whose names have the two cited endings.

[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply scripts/kubestellar-snapshot.sh:442]: Also, you might want to indicate whether the CRD is "established". That is the Condition that means that the apiserver has accepted the definition and finished putting it into effect.

[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply scripts/kubestellar-snapshot.sh:442]:
```console
mspreitz@mjs13 kubestellar % kubectl --context kind-kubeflex get crds bindingpolicies.control.kubestellar.io -o jsonpath='{.status.conditions[?(@.type=="Established")].status}'
True
```

File: scripts/kubestellar-snapshot.sh (hunk 3 above)
Comment (francostellari) [reply scripts/kubestellar-snapshot.sh:370]: I change job -> pod
I did not need to strip the `pod/` prefix to have it work but I have changed it anyhow

File: scripts/kubestellar-snapshot.sh (hunk 4 above)
Comment (francostellari) [reply scripts/kubestellar-snapshot.sh:372]: the output of the command in the if will print to screen...showing the error.
This is followed by the error text above in red

File: scripts/kubestellar-snapshot.sh [hunk 7]
```diff
@@ -21,7 +21,7 @@ set -e
 # Global variables
 TIMESTAMP="$(date +%F_%T)"
 TMPFOLDER="$(mktemp -d -p . "kubestellar-snapshot-XXXX")"
-trap 'rm -rf "$TMPFOLDER"' EXIT
+trap on_exit EXIT
```
Comment (MikeSpreitzer) [inline scripts/kubestellar-snapshot.sh:24]: I would feel more comfortable if `on_exit` were defined by now.

File: scripts/kubestellar-snapshot.sh (hunk 4 above)
Comment (MikeSpreitzer) [reply scripts/kubestellar-snapshot.sh:387]: Do you mean the output after filtering by `| grep "toomanyrequests"`? That may lack enough context to be understood.

File: scripts/kubestellar-snapshot.sh [hunk 8]
```diff
@@ -163,6 +163,37 @@ get_kubeconfig() {
...
+# List all CRDs of interest
+list_crds() {
+    modifier="$1" # kubeconfig modifier
+    pattern="$2" # matching pattern
+    indent="$3" # indentation
+
+    echo "$indent- Found CRDs:"
+
+    kubectl $modifier get crds --no-headers -o name | grep "$pattern" | while read -r crd; do
+        echo -n -e "$indent  - ${COLOR_INFO}${crd##*/}crd${COLOR_NONE}: established="
```
Comment (MikeSpreitzer) [inline scripts/kubestellar-snapshot.sh:175]: What is the literal "crd" here for?

File: scripts/kubestellar-snapshot.sh [hunk 9]
```diff
@@ -436,12 +477,12 @@ for i in "${!cps[@]}" ; do # for all control planes in context ${context}
         if [[ "${cp_pch[cp_n]}" =~ ^its ]] ; then
             containers=$(kubectl --context $helm_context -n "${cp_ns[cp_n]}" get pod $its_pod -o jsonpath='{.spec.containers[*].name}')
             for ctr in $containers; do
-                { kubectl --context $helm_context -n "${cp_ns[cp_n]}" logs $its_pod -c "$ctr" || true; } > "$OUTPUT_FOLDER/$name/its-job-${ctr}.log"
+                { kubectl --context $helm_context -n "${cp_ns[cp_n]}" logs $its_pod -c "$ctr" 2> /dev/null || true; } > "$OUTPUT_FOLDER/$name/its-job-${ctr}.log"
```
Comment (MikeSpreitzer) [inline scripts/kubestellar-snapshot.sh:480]: Still not loving this discard of stderr

File: scripts/kubestellar-snapshot.sh [hunk 10]
```diff
@@ -436,12 +477,12 @@ for i in "${!cps[@]}" ; do # for all control planes in context ${context}
...
             done
-            kubectl --context $helm_context -n "$status_ns" logs $status_pod -c status-controller > "$OUTPUT_FOLDER/$name/status-addon.log"
+            kubectl --context $helm_context -n "$status_ns" logs $status_pod -c status-controller > "$OUTPUT_FOLDER/$name/status-addon.log" 2> /dev/null || true
```
Comment (MikeSpreitzer) [inline scripts/kubestellar-snapshot.sh:482]: Still not loving this discard of stderr

File: scripts/kubestellar-snapshot.sh [hunk 11]
```diff
@@ -436,12 +477,12 @@ for i in "${!cps[@]}" ; do # for all control planes in context ${context}
...
         else
-            kubectl --context $helm_context -n "${cp_ns[cp_n]}" logs $kubestellar_pod > "$OUTPUT_FOLDER/$name/kubestellar-controller.log"
-            kubectl --context $helm_context -n "${cp_ns[cp_n]}" logs $trasport_pod -c transport-controller > "$OUTPUT_FOLDER/$name/transport-controller.log"
+            kubectl --context $helm_context -n "${cp_ns[cp_n]}" logs $kubestellar_pod > "$OUTPUT_FOLDER/$name/kubestellar-controller.log" 2> /dev/null || true
```
Comment (MikeSpreitzer) [inline scripts/kubestellar-snapshot.sh:484]: Still not loving this discard of stderr

File: scripts/kubestellar-snapshot.sh [hunk 12]
```diff
@@ -436,12 +477,12 @@ for i in "${!cps[@]}" ; do # for all control planes in context ${context}
...
+            kubectl --context $helm_context -n "${cp_ns[cp_n]}" logs $trasport_pod -c transport-controller > "$OUTPUT_FOLDER/$name/transport-controller.log" 2> /dev/null || true
```
Comment (MikeSpreitzer) [inline scripts/kubestellar-snapshot.sh:485]: Still not loving this discard of stderr

File: scripts/kubestellar-snapshot.sh (hunk 8 above)
Comment (MikeSpreitzer) [reply scripts/kubestellar-snapshot.sh:175]: Here is some example logging from a test of commit d28c4c509b83e9619f94ce6ec76fdda2428121c1:

```console
  - bindingpolicies.control.kubestellar.iocrd: established=true
```

File: scripts/kubestellar-snapshot.sh (hunk 7 above)
Comment (MikeSpreitzer) [reply scripts/kubestellar-snapshot.sh:24]: I tested commit d28c4c509b83e9619f94ce6ec76fdda2428121c1, and got no `kubestellar-snapshot.tar.gz` file.

File: scripts/kubestellar-snapshot.sh (hunk 8 above)
Comment (francostellari) [reply scripts/kubestellar-snapshot.sh:175]: typo

File: scripts/kubestellar-snapshot.sh (hunk 9 above)
Comment (francostellari) [reply scripts/kubestellar-snapshot.sh:480]: ok, I think I changed them all this time

File: scripts/kubestellar-snapshot.sh (hunk 7 above)
Comment (MikeSpreitzer) [reply scripts/kubestellar-snapshot.sh]: Oh, right.

File: scripts/kubestellar-snapshot.sh (hunk 4 above)
Comment (francostellari) [reply scripts/kubestellar-snapshot.sh:389]: If I look at your post https://github.com/kubestellar/kubestellar/issues/2786
It seems to me that the log file you posted only has 2 lines only one of which is meaningful.
The error is followed by the script suggesting a possible issue.

File: scripts/kubestellar-snapshot.sh (hunk 7 above)
Comment (MikeSpreitzer) [reply scripts/kubestellar-snapshot.sh]: I see the latest reordering.
