### PR TITLE
✨ add step to install post-install hooks in e2e tests and upgrade kflex to v0.4.2

### LINKED ISSUE #1737: bug: post-create-hooks are missing in e2e after update to kubeflex v0.4.2
### Describe the bug

As agreed previously, kubeflex removed the default pch for ocm and kubestellar. The e2e script now fails with kubeflex v0.4.2 because of missing hooks.

```
$ k --context kind-kubeflex get cps imbs1 -o yaml
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: ControlPlane
metadata:
  creationTimestamp: "2024-02-09T20:59:32Z"
  finalizers:
  - kflex.kubestellar.org/finalizer
  generation: 1
  name: imbs1
  resourceVersion: "1135"
  uid: dab6f932-60c7-4f65-a158-8f967b756d15
spec:
  backend: shared
  postCreateHook: ocm
  type: vcluster
status:
  conditions:
  - lastTransitionTime: "2024-02-09T21:00:46Z"
    lastUpdateTime: "2024-02-09T21:00:46Z"
    message: ""
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-02-09T21:00:46Z"
    lastUpdateTime: "2024-02-09T21:00:46Z"
    message: error retrieving post create hook ocm PostCreateHook.tenancy.kflex.kubestellar.org
      "ocm" not found
    reason: ReconcileError
    status: "False"
    type: Synced
  observedGeneration: 0
  secretRef:
    inClusterKey: config-incluster
    key: config
    name: vc-vcluster
    namespace: imbs1-system
```    

### Steps To Reproduce

upgrade KubeFlex CLI to v0.4.2 and run the e2e tests.

### Expected Behavior

Should not fail.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pdettori**
## Summary

add step to install post-install hooks in e2e tests and upgrade kflex to v0.4.2

## Related issue(s)

Fixes #1737

### CODE REVIEW

File: test/e2e/common/setup-kubestellar.sh [hunk 1]
```diff
@@ -29,6 +29,14 @@ fi
 kflex init --create-kind $disable_chatty_status
 : Kubeflex kind cluster created.
 
+:
+: -------------------------------------------------------------------------
+: Install the post-create-hooks for ocm and kubstellar controller manager
+:
+kubectl apply -f ${SRC_DIR}/../../../config/postcreate-hooks/ocm.yaml
+kubectl apply -f ${SRC_DIR}/../../../config/postcreate-hooks/kubestellar.yaml
```
Comment (MikeSpreitzer) [inline test/e2e/common/setup-kubestellar.sh:37]: I think this one is irrelevant, because the commands below for creating the WDS do not use a PostCreateHook

Comment (waltforme) [reply test/e2e/common/setup-kubestellar.sh:37]: I agree that the `kubestellar` hook is not used in today's tests (which builds the KS controller manager from source). The reason that I think this line should be in this script is that it can be useful in the future, for https://github.com/kubestellar/kubestellar/issues/1590, as a 'common setup' step.

Comment (effi-ofer) [reply test/e2e/common/setup-kubestellar.sh:37]: I am not commenting on whether this is right PR for these lines, but I wanted to point out that we will need them for tests of release images.

File: test/e2e/common/setup-kubestellar.sh [hunk 2]
```diff
@@ -29,6 +29,14 @@ fi
 kflex init --create-kind $disable_chatty_status
 : Kubeflex kind cluster created.
 
+:
+: -------------------------------------------------------------------------
+: Install the post-create-hooks for ocm and kubstellar controller manager
+:
+kubectl apply -f ${SRC_DIR}/../../../config/postcreate-hooks/ocm.yaml
```
Comment (MikeSpreitzer) [inline test/e2e/common/setup-kubestellar.sh:36]: BTW, this needs to become irrelevant too. Currently this line is using something built from an older version of this same git repo. Instead it should use the local copy of the repo, as is done in place of the other PostCreateHook.

Comment (pdettori) [reply test/e2e/common/setup-kubestellar.sh:36]: @MikeSpreitzer can you explain more precisely what do you mean by "local copy of the repo" for the ocm post-create-hook ?
