### PR TITLE
🐛  Stop thrashing workload objects in the WEC, when max-num-wrapped is 1

### LINKED ISSUE #2634: bug: Pods for a completed Job start again
### Describe the bug

My environment:
k3d version v5.7.4
k3s version v1.30.4-k3s1 (default)
KubeStellar: 0.25.1 

I create a job in the mgmt cluster, it gets pulled to a WEC  and runs to completion. When the job completes I start another ( same job spec). I create multiple jobs this way. What I notice eventually on the WEC is that pods for a job, which previously completed, start again. This happens with KS v.0.25.0 and 0.25.1. In testing I've removed Kueue and my Kueue-KS integration controllers so its just KS in the picture. Below are two images, one showing all pods in completed state; and another showing the previously completed pods as running again.

image

I start a new job: sample-job-8qksl. Note that previously completed pods for a job sample-job-fmfzw are in Running state.

image

Below are manifestworks, bp, binding, and my job spec:
[mw1.txt](https://github.com/user-attachments/files/17937453/mw1.txt)
[mw3.txt](https://github.com/user-attachments/files/17937454/mw3.txt)
[mw4.txt](https://github.com/user-attachments/files/17937455/mw4.txt)
[mw5.txt](https://github.com/user-attachments/files/17937456/mw5.txt)
[wec-klusterlet.log](https://github.com/user-attachments/files/17937457/wec-klusterlet.log)

Job:
```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue-ks
    kubestellar.io/cluster: cluster2
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["50s"]
        resources:
          requests:
            cpu: 1
            memory: "200Mi"
          limits:
            memory: "200Mi"
            cpu: 1
      restartPolicy: Never
```
BP:
```
apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  creationTimestamp: "2024-11-27T16:01:04Z"
  finalizers:
  - bindingpolicy.kubestellar.io/kscontroller
  generation: 1
  name: cluster2
  resourceVersion: "1636"
  uid: 44627ace-a2b4-490d-aba4-d6bb3418b299
spec:
  clusterSelectors:
  - matchLabels:
      location-group: edge
      name: cluster2
  downsync:
  - createOnly: true
    objectSelectors:
    - matchLabels:
        kubestellar.io/cluster: cluster2
  wantSingletonReportedState: true
status:
  observedGeneration: 1
```
Binding:
```
apiVersion: control.kubestellar.io/v1alpha1
kind: Binding
metadata:
  creationTimestamp: "2024-11-27T16:01:06Z"
  finalizers:
  - transport.kubestellar.io/object-cleanup
  generation: 120
  name: cluster2
  ownerReferences:
  - apiVersion: control.kubestellar.io/v1alpha1
    blockOwnerDeletion: false
    controller: true
    kind: BindingPolicy
    name: cluster2
    uid: 44627ace-a2b4-490d-aba4-d6bb3418b299
  resourceVersion: "4013"
  uid: 0d1a89a8-9868-4de6-8a3a-007ef2c1db7b
spec:
  destinations:
  - clusterId: cluster2
  workload:
    clusterScope:
    - createOnly: true
      group: galaxy.kubestellar.io
      name: cluster2
      resource: clustermetrics
      resourceVersion: "4009"
      version: v1alpha1
    namespaceScope:
    - createOnly: true
      group: batch
      name: sample-job-4z8jx
      namespace: default
      resource: jobs
      resourceVersion: "2384"
      version: v1
    - createOnly: true
      group: batch
      name: sample-job-8qksl
      namespace: default
      resource: jobs
      resourceVersion: "3087"
      version: v1
    - createOnly: true
      group: batch
      name: sample-job-d7bgf
      namespace: default
      resource: jobs
      resourceVersion: "2729"
      version: v1
    - createOnly: true
      group: batch
      name: sample-job-fmfzw
      namespace: default
      resource: jobs
      resourceVersion: "3085"
      version: v1
status:
  observedGeneration: 120
```

### Steps To Reproduce

See above

### Expected Behavior

Pods with Completed state should not restart.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR stops the thrashing of workload objects in a WEC (see #2634) IF the transport-controller's max-num-wrapped is 1. The trick is to make the name of the `ManifestWork` a function of its one and only workload object.

This PR is built on #2641, and I will rebase this one if that one merges first.

Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-no-thrash/direct/release-notes/#0260-alpha1

## Related issue(s)

Hopefully this will fix #2634 but I want to wait for confirmation from @cwiklik before closing that Issue.

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
/cc @vMaroon 
/cc @waltforme 
/cc @nirrozenbaum 
@cwiklik 
@eaepstein

File: test/e2e/ginkgo/multiple_cluster_deployment_test.go [hunk 1]
```diff
@@ -131,6 +133,28 @@ var _ = ginkgo.Describe("end to end testing", func() {
...
+			util.CreateDeployment(ctx, wds, ns, "enginx",
+				map[string]string{
+					"app.kubernetes.io/name":         "nginx",
+					"test.kubestellar.io/test-label": "here",
+				})
+			util.ValidateNumDeployments(ctx, "wec1", wec1, ns, 3)
+			util.ValidateNumDeployments(ctx, "wec2", wec2, ns, 3)
+			dep1c := util.GetDeployment(ctx, wec1, ns, "nginx")
+			dep2c := util.GetDeployment(ctx, wec2, ns, "nginx")
+			gomega.Expect(dep1c.UID).To(gomega.Equal(dep1.UID))
```
Comment (waltforme) [inline test/e2e/ginkgo/multiple_cluster_deployment_test.go:156]: Trying to check my understanding. What can we infer from the fact that UIDs are equal?

Comment (MikeSpreitzer) [reply test/e2e/ginkgo/multiple_cluster_deployment_test.go:156]: If an API object is deleted and later another is created with the same name, the replacement will have a different UID. Constant UID shows that the object has not been deleted and replaced.
