### PR TITLE
🐛 Fixes to getRestConfig and callers

### LINKED ISSUE #2131: bug: control-plane waiting logic has gaps
### Describe the bug

https://github.com/kubestellar/kubestellar/blob/223360a38d01b5405c0056573c730ca846ca76d7/pkg/util/kubeconfig.go#L68-L125 will fail if there are some ITS control planes and a specific one is requested but does not exist yet. The func that is repeated until success should include looking for the specifically requested control plane, if there is one.

### Steps To Reproduce

See above.

### Expected Behavior

No spurious failure.

### Additional Context

I noticed this while working on #2127

### LINKED ISSUE #2133: bug: labelKey ignored in GetWDSKubeconfig
### Describe the bug

https://github.com/kubestellar/kubestellar/blob/223360a38d01b5405c0056573c730ca846ca76d7/pkg/util/kubeconfig.go#L73-L156 uses the given `labelKey` in log and error messages but not in the actual query.

### Steps To Reproduce

Look at the code.

### Expected Behavior

Either the parameter makes a difference or does not exist.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR removes the spurious parameter for the name of the label that holds a ControlPlane's "type" for KubeStellar purposes (WDS vs ITS).

This PR also fixes the wait loop in pkg/util.getRestConfig to wait for the right condition, not too much and not too little.

## Related issue(s)

Fixes #2131
Fixes #2133

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
/cc @pdettori 
/cc @vMaroon 
@francostellari

File: pkg/util/kubeconfig.go [hunk 1]
```diff
@@ -61,7 +61,7 @@ func GetWDSKubeconfig(logger logr.Logger, wdsName, wdsLabel string) (*rest.Confi
 			return nil, "", err
 		}
 	}
-	logger.Info("using label", "key", label.Key, "value", label.Value)
+	logger.Info("Using label", "wdsName", wdsName, "keyJustKidding", label.Key, "value", label.Value)
```
Comment (pdettori) [inline pkg/util/kubeconfig.go:64]: Why the "keyJustKidding" in the log message? It seems confusing. Also, it says "using label" but then it prints the wdsName and value. I would change the log pattern this way:

logger.Info("Using label",  "name", label.Key, "value", label.Value,"wdsName",wdsName)

File: pkg/util/kubeconfig.go [hunk 2]
```diff
@@ -75,53 +75,50 @@ func getRestConfig(logger logr.Logger, cpName, labelKey, labelValue string) (*re
...
 	kubeClient := *kslclient.GetClient()
-	list := &kfv1aplha1.ControlPlaneList{}
 	labelSelector := labels.SelectorFromSet(labels.Set(map[string]string{
 		ControlPlaneTypeLabel: labelValue,
 	}))
+	var targetCP *kfv1aplha1.ControlPlane
 
 	// wait until there are control planes with supplied labels
-	logger.Info("waiting for cp with label", "key", labelKey, "value", labelValue)
+	logger.Info("Waiting for cp with label", "cpName", cpName, "keyJustKidding", labelKey, "value", labelValue)
```
Comment (pdettori) [inline pkg/util/kubeconfig.go:84]: Same comment as above, I suggest changing to 

logger.Info("Waiting for cp with label",  "name", labelKey, "value", labelValue, "cpName", cpName)

File: pkg/util/kubeconfig.go [hunk 3]
```diff
@@ -75,53 +75,50 @@ func getRestConfig(logger logr.Logger, cpName, labelKey, labelValue string) (*re
...
+		if cpName != "" {
+			cp := &kfv1aplha1.ControlPlane{}
+			err := kubeClient.Get(ctx, client.ObjectKey{Name: cpName}, cp, &client.GetOptions{})
+			if err == nil {
+				targetCP = cp
+				return true, nil
+			}
+			return false, nil
+		}
+		list := &kfv1aplha1.ControlPlaneList{}
```
Comment (pdettori) [inline pkg/util/kubeconfig.go:95]: The original intent when this code was initially written was to allow selection of a WDS or ITS either by name or label. If the user does not specify a label, the default label is used. So far, the only usage pattern has been to specify the name for the WDS and just use the default label for the ITS (that is, an ITS name was not required).  Since kubeflex may create also control plane that may not necessarily be used as WDS or ITSs it may still make sense to require to have a label in each to indicate the role. If we relax the restriction on ITSs, we should allow more then one but then we would need to associate WDSs with ITSs.

File: pkg/util/kubeconfig.go (hunk 1 above)
Comment (MikeSpreitzer) [reply pkg/util/kubeconfig.go:64]: The "JustKidding" part is an interim marker that this needs to be fixed as part of fixing #2133 , and a warning to anyone who reads such a log message before the fix.

File: pkg/util/kubeconfig.go (hunk 3 above)
Comment (MikeSpreitzer) [reply pkg/util/kubeconfig.go:95]: > So far, the only usage pattern has been to specify the name for the WDS and just use the default label for the ITS

We have begun changing this, allowing more than one ITS cp in KubeFlex. @francostellari is working right now on an all-in-one chart that allows a general number of WDSes, a general number of ITSes, and a general selection of ITS for each WDS.

> it may still make sense to require to have a label in each to indicate the role

Indeed it might, perhaps for general orderliness or informing something else. But when the user has indicated the name of the ITS control plane to use, I see no reason to refuse based on labels.

File: pkg/util/kubeconfig.go (hunk 1 above)
Comment (MikeSpreitzer) [reply pkg/util/kubeconfig.go]: The force-push to 9df116506 changes the order as suggested here.

File: pkg/util/kubeconfig.go (hunk 2 above)
Comment (MikeSpreitzer) [reply pkg/util/kubeconfig.go]: The force-push to https://github.com/kubestellar/kubestellar/commit/9df1165065fa60b4c82b04e2c716b51735b26af5 changes the order as suggested here.

File: pkg/util/kubeconfig.go (hunk 1 above)
Comment (MikeSpreitzer) [reply pkg/util/kubeconfig.go]: The force-push to 359b169b7 makes this moot.

**Review by pdettori — COMMENTED** [review]
/lgtm
