### PR TITLE
🐛 Added ginkgo prereq test only when --test-type=ginkgo

### LINKED ISSUE #3712: bug: E2E test does not check ginkgo prereq
### Describe the bug

The E2E test script does not check the prereq for ginkgo (which is indeed a prereq when running the ginkgo-based test suite).

### Output from KubeStellar-Snapshot.sh

N/A

### Steps To Reproduce

Without ginkgo installed on your machine, run `test/e2e/run.sh --test-type ginkgo`.

### Expected Behavior

Lack of ginkgo installation is reported in the prereq-checking phase.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xonas1101**
## Summary

Add a prereq check for `ginkgo` in the E2E runner script when
`--test-type ginkgo` is used.

## Related issue(s)

Fixes #3712

### CODE REVIEW

File: test/e2e/run-test.sh [hunk 1]
```diff
@@ -71,6 +71,17 @@ case "$test" in
...
+# Check ginkgo prereq only if running ginkgo tests
+if [ "$test" == "ginkgo" ]; then
+    if ! command -v ginkgo >/dev/null 2>&1; then
+        echo "$0 ginkgo is required to run ginkgo-based E2E tests."
+        echo "Make sure it is installed and available in your PATH."
+        echo "Install it with:"
+        echo "  go install github.com/onsi/ginkgo/v2/ginkgo@latest"
+        exit 1
+    fi
+fi
```
[the remark this answers is not in the document]
Comment (xonas1101) [reply test/e2e/run-test.sh]: @MikeSpreitzer do we need this? or is mine ok?

[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply test/e2e/run-test.sh]: I very much agree with Copilot here.

**Comment by xonas1101** [comment]
@MikeSpreitzer I have made the changes as requested by Copilot.

File: scripts/check_pre_req.sh [hunk 2]
```diff
@@ -125,6 +125,15 @@ is_installed_go() {
         'go version 1.23'
 }
 
+is_installed_ginkgo() {
+    is_installed 'Ginkgo' \
+        'ginkgo' \
+        'ginkgo version' \
+        'ginkgo version' \
+        'go install github.com/onsi/ginkgo/v2/ginkgo@latest' \
```
Comment (MikeSpreitzer) [inline scripts/check_pre_req.sh]: Requesting the latest version of a dependency is always a logic time-bomb and a supply chain vulnerability. Please put a specific release here.

Comment (xonas1101) [reply scripts/check_pre_req.sh]: ok @MikeSpreitzer I'll get to it.

Comment (xonas1101) [reply scripts/check_pre_req.sh]: I'll use v2.22.2 as in go.mod

**Comment by xonas1101** [comment]
@MikeSpreitzer I have added a specific release, while i was on it i also added a minimum required version. I dont know if that was required.

**Comment by MikeSpreitzer** [comment]
> i also added a minimum required version

That's not bad. But it shouldn't be higher than necessary. I am pretty sure that 2.22.2 is higher than necessary.

I do not know the minimum that is acceptable. Maybe guess 2.0 and we can fix it later if we find a problem with that.

**Comment by xonas1101** [comment]
ok, i'll change it to 2.0 then.
