### PR TITLE
🐛 Add status clearing for multiwec

### LINKED ISSUE #3518: bug: handle status clearing for multiwec
### Describe the bug

current implementation in **singletonstatus.go** only handles singletonstatus clearing when the singleton flag is set to false from true. It doesn't handles the status clearing for multiwec when flag is changed from true to false. 

### Output from KubeStellar-Snapshot.sh

_No response_

### Steps To Reproduce

1. Create a binding policy with **wantMultiWECReportedState: true**
2. Deploy the app
3. See the aggregated status in WDS.
4. Update  **wantMultiWECReportedState:** to false
5. You can still see aggregated status in WDS 

### Expected Behavior

Change in **wantMultiWECReportedState** to false from true should clear the status in WDS. 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by gaurab-khanal**
## Summary
This PR handles status clearing for multiwec when the **wantMultiWECReportedState** is set to false from true. 

## Related issue(s)

Fixes #3518

### CODE REVIEW

File: pkg/status/singletonstatus.go [hunk 1]
```diff
@@ -93,10 +93,16 @@ func (c *Controller) syncWorkloadObject(ctx context.Context, wObjID util.ObjectI
...
+	// handles status clearing for singleton
 	if err := c.updateObjectStatus(ctx, wObjID, nil, c.listers, false); err != nil {
 		return err
 	}
 
+	// handles status clearing for multiwec
+	if err := c.updateObjectStatus(ctx, wObjID, nil, c.listers, true); err != nil {
+		return err
+	}
+
```
Comment (MikeSpreitzer) [inline pkg/status/singletonstatus.go]: No. `c.updateObjectStatus` (already called above) should ensure that _both_ labels are set correctly. When `status == nil`, that means both labels should be absent.

Comment (gaurab-khanal) [reply pkg/status/singletonstatus.go]: Please check. I have made requested chages.

File: pkg/status/workstatus.go [hunk 2]
```diff
@@ -162,10 +170,21 @@ func (c *Controller) updateObjectStatus(ctx context.Context, objectIdentifier ut
 		}
 		logger.V(5).Info("Updated status of workload object", "objectIdentifier", objectIdentifier)
 	}
-	if haveReturn && !wantReturn {
-		// Need to remove the label alleging that the workload object has returned reported state
-		return c.handleStatusReturnLabel(ctx, unstrObj, objectIdentifier.GVR(), false, labelKey)
+
+	if haveSingleton && !wantReturn {
```
Comment (MikeSpreitzer) [inline pkg/status/workstatus.go]: What if `haveSingleton && !wantSingleton` (because wantMultiWEC)?

Comment (gaurab-khanal) [reply pkg/status/workstatus.go]: I couldn't understand what you are asking for. Please describe it.

Comment (MikeSpreitzer) [reply pkg/status/workstatus.go]: If `haveSingleton && !wantSingleton` then the label saying that the status came from a single WEC needs to be removed --- but I do not see the current version of this PR doing that.
