### PR TITLE
✨ Accurate labeling on ManifestWorks

### LINKED ISSUE #1541: bug: assign correctly placement labels in transport manifest when different placements select overlapping groups of clusters
### Describe the bug

 The current logic for assigning placement labels  for an object that has overlapping placement with overlapping matching clusters is not correct. This is because of a shortcut that was taken in the placement logic implementation.
 
For example, object 1 has matching placement 1, that selects clusters 1 and 2, and placement 2, that selects clusters 2 and 3. The list of clusters for the object is cluster 1, cluster 2, cluster 3. The shortcut implementation adds the label for placement 1 and 2 to all copies of the manifest in cluster 1, 2 and 3.

### Steps To Reproduce

Test by creating overlapping placements as described in the bug, and examine the labels in the ManifestWork.

### Expected Behavior

the correct implementation should add the label for placement 1 on cluster 1, for placement 1 and 2 on cluster 2, and for placement 2 on cluster 3.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by waltforme**
## Summary
This PR applies accurate 'managed-by' labels on Manifestworks which are delivered by the placement controller, thus handles #1541.

#1541 already clearly described the issue. Below is a visualization/example of that situation.
image

## Related issue(s)
Closes #1541

### CODE REVIEW

**Comment by waltforme** [comment]
Here are the tests I did in my setup with 3 managed clusters. The workload object I'm checking is a namespace `nginx`.
```
ubuntu@ip-172-31-38-158:~/kubestellar$ kc --context imbs1 -n cluster1 get manifestwork v1-namespace--nginx -oyaml | yq .metadata.labels
managed-by.kubestellar.io/wds1.nginx-edge: "true"
ubuntu@ip-172-31-38-158:~/kubestellar$ kc --context imbs1 -n cluster2 get manifestwork v1-namespace--nginx -oyaml | yq .metadata.labels
managed-by.kubestellar.io/wds1.nginx-dev: "true"
managed-by.kubestellar.io/wds1.nginx-edge: "true"
ubuntu@ip-172-31-38-158:~/kubestellar$ kc --context imbs1 -n cluster3 get manifestwork v1-namespace--nginx -oyaml | yq .metadata.labels
managed-by.kubestellar.io/wds1.nginx-dev: "true"
```

**Comment by nirrozenbaum** [comment]
we’re in the process of reviewing and merging of pluggable transport and all of this code will not exist. in addition, the way that transport works is different than what was done here (we wrap multiple objects not one).
I suggest holding with this PR until pluggable transport is merged and then to solve it with the new design and code.

File: pkg/placement/controller.go [hunk 1]
```diff
@@ -441,7 +442,46 @@ func (c *Controller) reconcile(ctx context.Context, key util.Key) error {
...
+					break
+				}
+			}
+			if matches {
+				placementNames = append(placementNames, plName)
+			}
+		}
+		manifest := ocm.WrapObject(obj)
+		util.SetManagedByPlacementLabels(manifest, c.wdsName, placementNames, singletonStatus)
+		err := reconcileManifest(c.ocmClient, manifest, clName)
```
Comment (ezrasilvera) [inline pkg/placement/controller.go:480]: Do we need to do the above operations in case there were no matches at all and placementNames is empty ?

File: pkg/placement/controller.go [hunk 2]
```diff
@@ -441,7 +442,46 @@ func (c *Controller) reconcile(ctx context.Context, key util.Key) error {
 	}
 
 	c.logger.Info("Delivering", "object", util.GenerateObjectInfoString(obj), "to clusters", clusters)
-	deliverObjectToManagedClusters(c.logger, c.ocmClient, obj, clusters, managedByPlacements, c.wdsName, singletonStatus)
+	for _, clName := range clusters {
+		// find which placement(s) select this managedCluster
+		placementNames := []string{}
+		for _, plName := range managedByPlacements {
+			plObj, err := c.getPlacementByName(plName)
+			if err != nil {
```
Comment (ezrasilvera) [inline pkg/placement/controller.go:450]: should we return an error if the error was for specific name? Maybe continue ?

File: pkg/placement/controller.go (hunk 1 above)
Comment (waltforme) [reply pkg/placement/controller.go:480]: Good question. My understanding is that we should always have a non-empty list because in order for each cluster to be included into the `clusters` list, there must be at least one placement(s) that select it.

File: pkg/placement/controller.go (hunk 2 above)
Comment (waltforme) [reply pkg/placement/controller.go:450]: I think we should return. Thoughts are: If we continue, we may end up with an incomplete list of `placementNames` for current cluster, thus an inaccurate set of labels on the ManifestWork. But I'm not 100% sure. Maybe @pdettori has a better view on this?

Comment (pdettori) [reply pkg/placement/controller.go:450]: @waltforme overall looks fine, but could all the added logic be implemented in `deliverObjectToManagedClusters` (changing / rewriting that function and its signature as you see fit) ?

File: pkg/placement/controller.go (hunk 1 above)
Comment (pdettori) [reply pkg/placement/controller.go:480]: At this point there should be a non-empty list of clusters (that was checked before) and  a non empty list of managedByPlacements - since the latter is not checked it seems like a good idea to check

**Review by pdettori — CHANGES_REQUESTED** [review]

File: pkg/placement/controller.go (hunk 2 above)
Comment (waltforme) [reply pkg/placement/controller.go]: Thanks for the suggestion. I packed the logic into a method (not a standalone function) on `c *Controller` because I see the logic relies on `c` in multiple places.

File: pkg/placement/controller.go (hunk 1 above)
Comment (waltforme) [reply pkg/placement/controller.go]: Done in the latest push.

**Review by pdettori — APPROVED** [review]
/lgtm
