### PR TITLE
🐛 Split ambiguous cr-validation test into two focused cases

### LINKED ISSUE #2673: Integration test confusion
```
		{name: "no-test-in-policy", specJSON: `{"downsync": [{"createOnly": true, "statusCollection": {"statusCollectors": ["phred"]}}]}`},
test/integration/controller-manager/cr-validation_test.go
```

Combines two failures in one now. It is intended to test the prohibition of an accept-all test. It now also fails due to the recent API change.

### PR DESCRIPTION
**Pull request by rishi-jat**
Description:
Split the ambiguous no-test-in-policy test into two separate cases: one for empty ObjectTest rejection, and one for the invalid statusCollection field. Each test now checks a single validation error as intended.

fixes #2673

### CODE REVIEW

**Comment by rishi-jat** [comment]
@MikeSpreitzer have a look to PR.

File: test/integration/controller-manager/cr-validation_test.go [hunk 1]
```diff
@@ -91,7 +91,10 @@ func TestBindingPolicyValidation(t *testing.T) {
 	}{
 		{name: "junk-field-in-spec", specJSON: `{"junk": 1}`, expectOK: false},
 		{name: "junk-field-in-policy", specJSON: `{"downsync": [{"junq": true}]}`},
-		{name: "no-test-in-policy", specJSON: `{"downsync": [{"createOnly": true, "statusCollection": {"statusCollectors": ["phred"]}}]}`},
+		// Test: empty ObjectTest (no selector fields, valid fields only)
+		{name: "empty-object-test", specJSON: `{"downsync": [{"createOnly": true}]}`, expectOK: false},
```
Comment (MikeSpreitzer) [inline test/integration/controller-manager/cr-validation_test.go]: FYI, `, expectOK: false` is unnecessary, since `false` is the default value for that field.

File: test/integration/controller-manager/cr-validation_test.go [hunk 2]
```diff
@@ -91,7 +91,10 @@ func TestBindingPolicyValidation(t *testing.T) {
...
+		// Test: use of now-invalid 'statusCollection' field (should fail OpenAPI validation)
+		{name: "invalid-statusCollection-field", specJSON: `{"downsync": [{"createOnly": true, "statusCollection": {"statusCollectors": ["phred"]}}]}`, expectOK: false},
```
Comment (MikeSpreitzer) [inline test/integration/controller-manager/cr-validation_test.go]: +1 on splitting one test of two ways to fail into two tests, one of each of the two ways to fail. Unfortunately, that is not what happened here; this test case still combines two ways to fail.

**Comment by rishi-jat** [comment]
@MikeSpreitzer Suggested changes are done have a look to PR.

**Comment by rishi-jat** [comment]
@MikeSpreitzer  The failing test appears to be a CI infrastructure issue rather than a problem with the test changes. Could you help investigate?

**Comment by rishi-jat** [comment]
@MikeSpreitzer 

The failing test appears to be a CI infrastructure issue rather than a problem with the test changes. The integration tests are passing, but the bash end-to-end test is failing with "error: context cluster1 does not exist". Could you help investigate?

**Comment by rishi-jat** [comment]
Thanks @MikeSpreitzer! Everything else is passing except the bash E2E test, which still seems infra-related. Please take a look when you get a chance and /lgtm if it looks good.

File: test/integration/controller-manager/cr-validation_test.go [hunk 3]
```diff
@@ -89,9 +89,12 @@ func TestBindingPolicyValidation(t *testing.T) {
...
 		expectOK bool
 	}{
-		{name: "junk-field-in-spec", specJSON: `{"junk": 1}`, expectOK: false},
+		{name: "junk-field-in-spec", specJSON: `{"junk": 1}`},
 		{name: "junk-field-in-policy", specJSON: `{"downsync": [{"junq": true}]}`},
-		{name: "no-test-in-policy", specJSON: `{"downsync": [{"createOnly": true, "statusCollection": {"statusCollectors": ["phred"]}}]}`},
+		// Test: empty ObjectTest (no selector fields, valid fields only)
+		{name: "empty-object-test", specJSON: `{"downsync": [{"createOnly": true}]}`},
+		// Test: use of now-invalid 'statusCollection' field (should fail OpenAPI validation)
+		{name: "invalid-statusCollection-field", specJSON: `{"downsync": [{"statusCollection": {"statusCollectors": ["phred"]}}]}`},
```
Comment (MikeSpreitzer) [inline test/integration/controller-manager/cr-validation_test.go:97]: This test case still has two errors. It BOTH (1) has an empty ObjectTest and (2) specifies the `statusCollection` field.

**Review by MikeSpreitzer — APPROVED** [review]
This is good enough to merge because it is progress. As noted above, it still has a problem; that can be addressed in follow-on.

/lgtm
/approve
Thanks!
