### PR TITLE
🐛 Add cleaning for Job objects

### LINKED ISSUE #1766: feature:  add denature for Jobs in the WDS
### Feature Description

This is a feature that is required when creating a job inside a WDS

A regular Kube API server sets some labels in the job object that should not be propagated down to the WECs.

This can be tested in a WDS: 

Apply a job:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: test-kfp
  labels:
    app.kubernetes.io/name: nginx-singleton
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```

After applying the job, several labels are added by the API server in the WDS.

```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"nginx-singleton"},"name":"pi","namespace":"test-kfp"},"spec":{"backoffLimit":4,"template":{"spec":{"containers":[{"command":["perl","-Mbignum=bpi","-wle","print bpi(2000)"],"image":"perl:5.34.0","name":"pi"}],"restartPolicy":"Never"}}}}
  creationTimestamp: "2024-02-15T20:57:52Z"
  generation: 1
  labels:
    app.kubernetes.io/name: nginx-singleton
  name: pi
  namespace: test-kfp
  resourceVersion: "1281831"
  uid: 1515c04b-7406-40b5-b799-46a536258999
spec:
  backoffLimit: 4
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 1515c04b-7406-40b5-b799-46a536258999
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        batch.kubernetes.io/controller-uid: 1515c04b-7406-40b5-b799-46a536258999
        batch.kubernetes.io/job-name: pi
        controller-uid: 1515c04b-7406-40b5-b799-46a536258999
        job-name: pi
    spec:
      containers:
      - command:
        - perl
        - -Mbignum=bpi
        - -wle
        - print bpi(2000)
        image: perl:5.34.0
        imagePullPolicy: IfNotPresent
        name: pi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
```

The Manifestwork shows the following error: 

```
 resourceStatus:
    manifests:
    - conditions:
      - lastTransitionTime: "2024-02-15T20:57:52Z"
        message: 'Failed to apply manifest: Job.batch "pi" is invalid: [spec.template.metadata.labels[controller-uid]:
          Invalid value: map[string]string{"batch.kubernetes.io/controller-uid":"1515c04b-7406-40b5-b799-46a536258999",
          "batch.kubernetes.io/job-name":"pi", "controller-uid":"1515c04b-7406-40b5-b799-46a536258999",
          "job-name":"pi"}: must be ''466083b2-5542-44bf-8452-3d8c22c6a162'', spec.template.metadata.labels[batch.kubernetes.io/controller-uid]:
          Invalid value: map[string]string{"batch.kubernetes.io/controller-uid":"1515c04b-7406-40b5-b799-46a536258999",
          "batch.kubernetes.io/job-name":"pi", "controller-uid":"1515c04b-7406-40b5-b799-46a536258999",
          "job-name":"pi"}: must be ''466083b2-5542-44bf-8452-3d8c22c6a162'', spec.selector:
          Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"batch.kubernetes.io/controller-uid":"1515c04b-7406-40b5-b799-46a536258999"},
          MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: `selector` not auto-generated]'
        reason: AppliedManifestFailed
        status: "False"
        type: Applied
      - lastTransitionTime: "2024-02-15T20:57:52Z"
        message: Resource is not available
        reason: ResourceNotAvailable
        status: "False"
        type: Available
      resourceMeta:
        group: batch
        kind: Job
        name: pi
        namespace: test-kfp
        ordinal: 0
        resource: jobs
        version: v1
      statusFeedback: {}

```

### Proposed Solution

 The added labels cannot be re-used in another cluster and need to be zero-ed

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR updates the generic transport controller code to remove the apiserver-maintained fields of a JobSpec.

The corresponding test enhancement will be done in #1824 or follow-on.

## Related issue(s)

This is an alternative to #1803, which we decided not to pursue (in favor of #1812).

Fixes #1766

### CODE REVIEW

File: pkg/transport/filtering/job.go [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+		return
+	}
+	delete(podLabels, "batch.kubernetes.io/controller-uid")
+	delete(podLabels, "batch.kubernetes.io/job-name")
+	delete(podLabels, "controller-uid")
+	delete(podLabels, "job-name")
+	err = unstructured.SetNestedMap(objectU, podLabels, "spec", "template", "metadata", "labels")
+	if err != nil {
+		logger.Error(err, "Inconceivable! Failed to update existing pod labels in Job", "namespace", object.GetNamespace(), "name", object.GetName())
+	}
```
Comment (nirrozenbaum) [inline pkg/transport/filtering/job.go:39]: I don't think the logger is needed here at all.
what is the purpose of this clean function?
to clean several labels from `spec.template.metadata.labels`.

if `spec.template.metadata.labels` is not found on the object, then just need to return, there's nothing to clean.

this log is adding noise without any need for it.

Comment (nirrozenbaum) [reply pkg/transport/filtering/job.go:39]: in line 37 this doesn't make sense even more. you log an error but then continue the handling.
if anyway you continue processing, then this log is not needed.

File: pkg/transport/filtering/job.go [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
+)
+
+func cleanJob(logger logr.Logger, object *unstructured.Unstructured) {
+	objectU := object.UnstructuredContent()
+	podLabels, found, err := unstructured.NestedMap(objectU, "spec", "template", "metadata", "labels")
+	if err != nil || !found {
+		logger.V(3).Error(nil, "Job lacks expected template labels", "namespace", object.GetNamespace(), "name", object.GetName(), "found", found, "err", err)
+		return
+	}
```
Comment (nirrozenbaum) [inline pkg/transport/filtering/job.go:31]: I would write these lines :
```
podLabels, found, _ := unstructured.NestedMap(objectU, "spec", "template", "metadata", "labels")
	!found {
		return
	}
```

File: pkg/transport/filtering/job.go [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+	delete(podLabels, "batch.kubernetes.io/controller-uid")
+	delete(podLabels, "batch.kubernetes.io/job-name")
+	delete(podLabels, "controller-uid")
+	delete(podLabels, "job-name")
+	err = unstructured.SetNestedMap(objectU, podLabels, "spec", "template", "metadata", "labels")
```
Comment (nirrozenbaum) [inline pkg/transport/filtering/job.go:36]: this error check is redundat. from `SetNestedMap documentation:
```
SetNestedMap sets the map[string]interface{} value of a nested field. Returns an error if value cannot be set because one of the nesting levels is not a map[string]interface{}.
```
you just got the labels from the object and deleted from of them. of course it's a valid map.

File: pkg/transport/filtering/job.go (hunk 1 above)
Comment (MikeSpreitzer) [reply pkg/transport/filtering/job.go:39]: The logging is there because we think the apiserver-managed fields will certainly be present. If they are not, it is a surprise to us. The logging is a basic attempt to make this surprise visible to us.

File: pkg/transport/filtering/job.go (hunk 3 above)
Comment (MikeSpreitzer) [reply pkg/transport/filtering/job.go:36]: Yeah, that's why the log message is "Inconceivable!".

**Comment by nirrozenbaum** [comment]
other than the logger which seems not needed and even confusing (logs error but continue processing) everything looks good to me.
if we can remove the logging I'm happy to lgtm the PR

File: pkg/transport/filtering/job.go [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+package filtering
+
+import (
+	"github.com/go-logr/logr"
+
+	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
+)
+
+func cleanJob(logger logr.Logger, object *unstructured.Unstructured) {
+	objectU := object.UnstructuredContent()
```
Comment (nirrozenbaum) [inline pkg/transport/filtering/job.go:26]: if you use in line 27 object.Object instead of objectU, then this line is redundant.

File: pkg/transport/filtering/job.go (hunk 3 above)
Comment (nirrozenbaum) [reply pkg/transport/filtering/job.go:36]: so do you agree this is a redundant error check?
if this is inconceivable, we don't need to check for error and add logs that this is inconceivable.
this is just adding noise with no reason

Comment (nirrozenbaum) [inline pkg/transport/filtering/job.go:36]: you can use here object.Object as well

File: pkg/transport/filtering/job.go (hunk 1 above)
Comment (MikeSpreitzer) [reply pkg/transport/filtering/job.go]: On second thought, I agree that complaining when the pod spec has no labels is being unnecessarily prickly. I have removed that.

OTOH, if the structure navigation fails, that is a more serious surprise. I have left logging in that case.

Comment (MikeSpreitzer) [reply pkg/transport/filtering/job.go]: I changed the "Inconceivable!" log message into a panic.

File: pkg/transport/filtering/job.go (hunk 2 above)
Comment (MikeSpreitzer) [reply pkg/transport/filtering/job.go]: Yes. That leaves `err != nil`, which is a more serious surprise.

File: pkg/transport/filtering/job.go (hunk 3 above)
Comment (MikeSpreitzer) [reply pkg/transport/filtering/job.go:39]: I changed this log statement into a panic.

File: pkg/transport/filtering/job.go (hunk 4 above)
Comment (MikeSpreitzer) [reply pkg/transport/filtering/job.go:26]: I prefer to use the procedural interface rather that directly accessing internal structure; the former is easier on evolution scenarios.

File: pkg/transport/filtering/job.go (hunk 3 above)
Comment (nirrozenbaum) [reply pkg/transport/filtering/job.go:39]: that change doesn't make it better.
we still have a check for a condition that can never happen.

there is no point in adding noise without any need.

In general I'm in favor of reliable code and adding as many checks as needed, when needed.
here the logging is just not needed.
you wrote it yourself  - `that condition can never be true`. then why are we checking it?

File: pkg/transport/filtering/job.go [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+	podLabels, found, err := unstructured.NestedMap(objectU, "spec", "template", "metadata", "labels")
+	if !found {
+		return
+	}
+	if err != nil {
+		logger.V(3).Error(nil, "Job object does not have expected struture, no spec.template.metadata.labels", "namespace", object.GetNamespace(), "name", object.GetName(), "err", err)
+		return
```
Comment (nirrozenbaum) [inline pkg/transport/filtering/job.go:33]: same here.. see documentation of unstructured:
```
NestedMap returns a deep copy of map[string]interface{} value of a nested field. Returns false if value is not found and an error if not a map[string]interface{}.
```
if you get false in `found` then it's not found. otherwise, only if the field is found but it's not a map - you'll get an error.
this is VERY redundant check that can never happen

**Comment by ezrasilvera** [comment]
@MikeSpreitzer Any chance you can  also add a Job related test into the existing e2e test for service ?  We don't even need to clean between them just test deploying a Job just after the service .

File: pkg/transport/filtering/job.go (hunk 3 above)
Comment (MikeSpreitzer) [reply pkg/transport/filtering/job.go:39]: For safety as the code is edited in the future. If we simply remove all mention of the possibility of an error here then it is easier for a future change to introduce the possibility of an error here without noticing.

File: pkg/transport/filtering/job.go (hunk 5 above)
Comment (MikeSpreitzer) [reply pkg/transport/filtering/job.go:33]: The type mismatch can happen at any point along the path from the root of the object.

Having this check makes this func less reliant on other parts of our codebase and Kubernetes. This func takes an unstructured object, whose schema is not guaranteed a priori ; it is only when coupled with a larger analysis that shows this func being associated with v1 of Job that we start to get confidence. Even then, full confidence is relying on a lot more Kubernetes code.

Comment (nirrozenbaum) [reply pkg/transport/filtering/job.go:33]: if your concern is type mismatch then you try to cast the object to job in the first line of the function. if cast fails it’s not a job and the function can return, cause this is cleaner function for jobs only.
again, for this no needed for any logger

File: pkg/transport/filtering/job.go (hunk 3 above)
Comment (nirrozenbaum) [reply pkg/transport/filtering/job.go:39]: not sure I understand your point here. 
this is v1. it must be backwards compatible. 
any future change in k8s job should keep the existing ux

Comment (nirrozenbaum) [reply pkg/transport/filtering/job.go:39]: if in the future there will be a case we need to check, we can always add log in the future. 
I’m not in favor of adding now “for the future”

File: pkg/transport/filtering/job.go (hunk 5 above)
Comment (MikeSpreitzer) [reply pkg/transport/filtering/job.go:33]: Do you mean "cast" as in a [Go type assertion](https://go.dev/ref/spec#Type_assertions)? I would not expect that to succeed here because the `runtime.Object` is a `*unstructured.Unstructured` not a `*appsv1.Job`.

My point is about the complexity of understanding the code. With error checking in the func, it has a reasonable reaction of code outside the func (e.g., in how it gets registered and called) changes.

This debate is less important than getting something merged. I give up.

Comment (MikeSpreitzer) [reply pkg/transport/filtering/job.go]: I removed the error checking.

**Comment by nirrozenbaum** [comment]
/lgtm
Thanks! 🙏🏼

**Comment by MikeSpreitzer** [comment]
Yes, @ezrasilvera , I am working on that.
/hold

**Comment by nirrozenbaum** [comment]
for understanding what's the issue, one can see the dump of the e2e test.
more specifically, you can see the manifestswork part, which contains the particular error that causes this test not to pass.
```
message: 'Failed to apply manifest: Job.batch "pi" is invalid: [spec.selector:
            Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"batch.kubernetes.io/controller-uid":"a5eb20af-aaf8-4b9f-ada1-63bef08fadf7"},
            MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: `selector` not auto-generated,
            spec.template.metadata.labels: Invalid value: map[string]string{"batch.kubernetes.io/controller-uid":"122ee598-7824-4fd3-aca7-18c7b7d3cff0",
            "batch.kubernetes.io/job-name":"pi", "controller-uid":"122ee598-7824-4fd3-aca7-18c7b7d3cff0",
            "job-name":"pi"}: `selector` does not match template `labels`]'
```

you are missing the cleaning of the label  `batch.kubernetes.io/controller-uid` from `spec.selector.matchLabels`.

**Comment by MikeSpreitzer** [comment]
@nirrozenbaum : yes, I saw that. The current code cleans both the selector and the pod template's labels.

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer maybe I’m missing something, where does the label batch.kubernetes.io/controller-uid gets cleaned from spec.selector.matchLabels?

**Comment by MikeSpreitzer** [comment]
The force-pushes above abandon the sophisticated approach of trimming selector and pod label content not mentioned in `managedFields` because I was not seeing _any_ `managedFields` content in the objects. The current draft of this PR does something simpler and oblivious: it removes selector and pod label content for "controller-uid".

File: pkg/transport/filtering/object_filtering_map.go [hunk 6]
```diff
@@ -43,9 +46,13 @@ type ObjectFilteringMap struct {
...
 func (filteringMap *ObjectFilteringMap) CleanObjectSpecifics(object *unstructured.Unstructured) {
-	filteringFunction, found := filteringMap.gvkToFilteringFunc[object.GetObjectKind().GroupVersionKind()]
+	gvk := object.GetObjectKind().GroupVersionKind()
+	filteringFunction, found := filteringMap.gvkToFilteringFunc[gvk]
 	if !found {
+		klog.V(4).InfoS("No specifics", "gvk", gvk)
 		return // if no filtering function was defined for this gvk, do not clean any field
+	} else {
+		klog.V(4).InfoS("Found specifics", "gvk", gvk)
 	}
```
Comment (nirrozenbaum) [inline pkg/transport/filtering/object_filtering_map.go:56]: can we remove the log from this function?
this will thrash the controller log on every object that is being wrapped, make it harder to follow the log.

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer left a single minor comment about the log in `CleanObjectSpecifics` func. 
other than that looks good.

File: test/e2e/object-fields-filtering/use-kubestellar.sh [hunk 7]
```diff
@@ -18,7 +18,7 @@ set -e # exit on error
 
 :
 : -------------------------------------------------------------------------
-: "Create a bindingpolicy in wds1 to deliver a service to one WEC."
+: "Create a bindingpolicy in wds1 to deliver difficult API objects to one WEC."
```
Comment (ezrasilvera) [inline test/e2e/object-fields-filtering/use-kubestellar.sh:21]: Why can't we just say to deliver Job and Service API objects.  Users may not know what difficult means here

File: pkg/transport/filtering/object_filtering_map.go [hunk 8]
```diff
@@ -43,9 +46,13 @@ type ObjectFilteringMap struct {
 }
 
 func (filteringMap *ObjectFilteringMap) CleanObjectSpecifics(object *unstructured.Unstructured) {
-	filteringFunction, found := filteringMap.gvkToFilteringFunc[object.GetObjectKind().GroupVersionKind()]
+	gvk := object.GetObjectKind().GroupVersionKind()
+	filteringFunction, found := filteringMap.gvkToFilteringFunc[gvk]
 	if !found {
+		klog.V(4).InfoS("No specifics", "gvk", gvk)
 		return // if no filtering function was defined for this gvk, do not clean any field
+	} else {
```
Comment (ezrasilvera) [inline pkg/transport/filtering/object_filtering_map.go:54]: why do we need the "else" here ?

File: pkg/transport/filtering/object_filtering_map.go [hunk 9]
```diff
@@ -31,6 +33,7 @@ type cleanObjectSpecificsFunction func(object *unstructured.Unstructured)
 func NewObjectFilteringMap() *ObjectFilteringMap {
 	filteringMap := map[schema.GroupVersionKind]cleanObjectSpecificsFunction{
 		corev1.SchemeGroupVersion.WithKind("Service"): cleanServiceFields,
+		batchv1.SchemeGroupVersion.WithKind("Job"):    cleanJob,
```
Comment (ezrasilvera) [inline pkg/transport/filtering/object_filtering_map.go:36]: nit:  cleanJobFields or change also to  cleanService  .  BTW, why not cleanJobObject and cleanServiceObject  ?

File: pkg/transport/filtering/object_filtering_map.go (hunk 6 above)
Comment (MikeSpreitzer) [reply pkg/transport/filtering/object_filtering_map.go]: That was an oversight. Fixed.

File: test/e2e/object-fields-filtering/use-kubestellar.sh (hunk 7 above)
Comment (MikeSpreitzer) [reply test/e2e/object-fields-filtering/use-kubestellar.sh]: reworded.

File: pkg/transport/filtering/object_filtering_map.go (hunk 8 above)
Comment (MikeSpreitzer) [reply pkg/transport/filtering/object_filtering_map.go]: Now that the unintended logging is removed, there is no longer an "else".

File: pkg/transport/filtering/object_filtering_map.go (hunk 9 above)
Comment (MikeSpreitzer) [reply pkg/transport/filtering/object_filtering_map.go:35]: Made the Service one shorter too.

File: pkg/transport/filtering/object_filtering_map.go (hunk 8 above)
Comment (ezrasilvera) [reply pkg/transport/filtering/object_filtering_map.go]: My point is that  you don't need it if the if has a return  inside

Comment (ezrasilvera) [reply pkg/transport/filtering/object_filtering_map.go]: but as it's gone in any case I'm closing. thanks

**Comment by ezrasilvera** [comment]
Thanks @MikeSpreitzer  It LGTM  I'll let @nirrozenbaum complete his review
