### PR TITLE
🐛Fix kind image loading problem when using a recent version of Docker

### LINKED ISSUE #3363: bug: create-kubestellar-demo-env.sh fails with "ctr: content digest not found" on WSL
### Describe the bug

When running the `create-kubestellar-demo-env.sh` script on a fresh Ubuntu WSL 2 environment, it consistently fails when trying to load the `vcluster` image into the `kind` cluster.

### Output from KubeStellar-Snapshot.sh

I did not run the snapshot script. However, the full terminal log from the failed `create-kubestellar-demo-env.sh` run is provided below in the "Additional Context" section. It includes all the prerequisite version checks.

### Steps To Reproduce

1. Set up an environment with Windows, Docker Desktop, and Ubuntu on WSL 2.
2. In the WSL 2 terminal, run the command: `bash <(curl -s https://raw.githubusercontent.com/kubestellar/kubestellar/main/scripts/create-kubestellar-demo-env.sh)`

### Expected Behavior

The script should complete successfully and set up the demo environment without errors.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

The script should complete successfully and set up the demo environment without errors.

#####THESE ARE THE LOGS#####
 time bash <(curl -s https://raw.githubusercontent.com/kubestellar/kubestellar/main/scripts/create-kubestellar-demo-env.sh)
Selected Kubernetes platform: kind
Checking container runtime...
Container runtime is running.
KubeStellar Version: 0.29.0-alpha.1
Checking that pre-req softwares are installed...
Checking pre-requisites for KubeStellar:
✔ KubeFlex (Kubeflex version: v0.9.1.a6b8746 2025-09-08T01:47:31Z)
  version (unstructured): Kubeflex version: v0.9.1.a6b8746 2025-09-08T01:47:31Z
     path: /usr/local/bin/kflex
✔ OCM CLI (:v0.10.1-0-g18a991c)
  version (unstructured): client                version :v0.10.1-0-g18a991c
     path: /usr/local/bin/clusteradm
✔ Helm (v3.19.0)
  version (unstructured): version.BuildInfo{Version:"v3.19.0", GitCommit:"3d8990f0836691f0229297773f3524598f46bda6", GitTreeState:"clean", GoVersion:"go1.24.7"}
     path: /usr/local/bin/helm
✔ helm can fetch public charts
✔ kubectl (v1.32.2)
  version (unstructured): Client Version: v1.32.2
     path: /usr/local/bin/kubectl
✔ Docker (Docker version 28.3.3, build 980b856)
  version (unstructured): Docker version 28.3.3, build 980b856
     path: /usr/bin/docker
✔ Kind (kind v0.23.0 go1.21.10 linux/amd64)
  version (unstructured): kind v0.23.0 go1.21.10 linux/amd64
     path: /usr/local/bin/kind
✔ fs.inotify.max_user_watches is 1048576
✔ fs.inotify.max_user_instances is 8192

Starting environment clean up...
Starting cluster clean up...
✔ Cluster space clean up has been completed

Starting context clean up...
Deleting cluster1 context...
deleted context cluster1 from /home/shiva/.kube/config
Deleting cluster2 context...
deleted context cluster2 from /home/shiva/.kube/config
✔ Context space clean up completed

Creating two kind clusters to serve as example WECs
✔ Cluster cluster1 was successfully created
✔ Cluster cluster2 was successfully created
Creating KubeFlex cluster with SSL Passthrough
Creating "kubeflex" kind cluster with SSL passthrougn and 9443 port mapping...
Creating cluster "kubeflex" ...
 ✓ Ensuring node image (kindest/node:v1.30.0) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kubeflex"
You can now use your cluster with:

kubectl cluster-info --context kind-kubeflex

Thanks for using kind! 😊
Installing an nginx ingress...
namespace/ingress-nginx created
serviceaccount/ingress-nginx created
serviceaccount/ingress-nginx-admission created
role.rbac.authorization.k8s.io/ingress-nginx created
role.rbac.authorization.k8s.io/ingress-nginx-admission created
clusterrole.rbac.authorization.k8s.io/ingress-nginx created
clusterrole.rbac.authorization.k8s.io/ingress-nginx-admission created
rolebinding.rbac.authorization.k8s.io/ingress-nginx created
rolebinding.rbac.authorization.k8s.io/ingress-nginx-admission created
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx created
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx-admission created
configmap/ingress-nginx-controller created
service/ingress-nginx-controller created
service/ingress-nginx-controller-admission created
deployment.apps/ingress-nginx-controller created
job.batch/ingress-nginx-admission-create created
job.batch/ingress-nginx-admission-patch created
ingressclass.networking.k8s.io/nginx created
validatingwebhookconfiguration.admissionregistration.k8s.io/ingress-nginx-admission created
Patching nginx ingress to enable SSL passthrough...
deployment.apps/ingress-nginx-controller patched
Waiting for nginx ingress with SSL passthrough to be ready...
Waiting for nginx ingress controller deployment to be rolled out...
Waiting for deployment spec update to be observed...
Waiting for deployment spec update to be observed...
Waiting for deployment "ingress-nginx-controller" rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for deployment "ingress-nginx-controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "ingress-nginx-controller" successfully rolled out
Waiting for nginx ingress controller pod to be ready...
pod/ingress-nginx-controller-75b64cfd58-qtjfs condition met
✔ Completed KubeFlex cluster with SSL Passthrough
Switched to context "kind-kubeflex".

Pulling container images local...
v0.15.2: Pulling from open-cluster-management/registration-operator
16.0.0-debian-11-r13: Pulling from kubestellar/postgresql
Digest: sha256:bb9b57190a31cb4ae440103d5b404b95a2c75c6d4895c365f16bdf36e556e397
Status: Image is up to date for quay.io/open-cluster-management/registration-operator:v0.15.2
quay.io/open-cluster-management/registration-operator:v0.15.2
Digest: sha256:3331ad89ba2d1af68e36521724440638be3834978ac8288c49e54929357143e6
Status: Image is up to date for quay.io/kubestellar/postgresql:16.0.0-debian-11-r13
quay.io/kubestellar/postgresql:16.0.0-debian-11-r13
0.16.4: Pulling from loft-sh/vcluster
Digest: sha256:84f70425f4dd64a85d4d904c5bdf9e71da79a91068136e4053fb0b54eb068ebb
Status: Image is up to date for ghcr.io/loft-sh/vcluster:0.16.4
ghcr.io/loft-sh/vcluster:0.16.4
v1.27.2-k3s1: Pulling from rancher/k3s
Digest: sha256:66d13a1d6f92c7aa41f7734d5e97526a868484071d7467feb69dd868ad653254
Status: Image is up to date for rancher/k3s:v1.27.2-k3s1
docker.io/rancher/k3s:v1.27.2-k3s1
Image: "ghcr.io/loft-sh/vcluster:0.16.4" with ID "sha256:84f70425f4dd64a85d4d904c5bdf9e71da79a91068136e4053fb0b54eb068ebb" not yet present on node "kubeflex-control-plane", loading...
ERROR: failed to load image: command "docker exec --privileged -i kubeflex-control-plane ctr --namespace=k8s.io images import --all-platforms --digests --snapshotter=overlayfs -" failed with error: exit status 1
Command Output: ctr: content digest sha256:9106d83981393d7489c50e7cfa87a9d30b78444420c22931094256e55f9d0e5f: not found

real    5m35.591s
user    0m30.185s

### PR DESCRIPTION
**Pull request by francostellari**
## Summary

Fix kind image loading problem when using a recent version of Docker by flattening the multi-platform images before loading them into kind

## Related issue(s)

Fixes #3363 #2797

### CODE REVIEW

File: scripts/create-kubestellar-demo-env.sh [hunk 1]
```diff
@@ -188,6 +188,14 @@ for image in "${images[@]}"; do
 done
 wait
 
+echo -e "\nFlatten images to single architecture to fix problems with kind load commands in recent Docker versions..."
+for image in "${images[@]}"; do
+    echo "FROM $image" | docker build -t "$image" -f- . &
```
Comment (MikeSpreitzer) [inline scripts/create-kubestellar-demo-env.sh]: This `.` means that in the course of doing that build, Docker tars up all of the user's local kubestellar repo (including .git) as the docker build context, right? Wouldn't it be much faster to use a smaller directory?

Comment (francostellari) [reply scripts/create-kubestellar-demo-env.sh]: No it doesn't, it's just the folder to be used as root for docker operations, you need add or copy commands in the dockerfile to add anything. As you see the dockerfile only has a FROM statement. It's very fast because there is nothing to do but recreate the manifest and suggest

Comment (MikeSpreitzer) [reply scripts/create-kubestellar-demo-env.sh]: @francostellari: There are two phases of building, and you spoke about the second but my concern is with the first. Before the Docker daemon does even the first step of the build, the CLI bundles up the context and sends it to the Docker daemon. Have a look at the "Best Practices" and "Notes and Limitations" sections of https://dockerbuild.com/reference/docker-build .

Comment (francostellari) [reply scripts/create-kubestellar-demo-env.sh]: I have changed the code to use an empty temp folder for the build.
This speeds up the build process on my computer from ~4s to ~2s for the total of 3 containers

File: scripts/create-kubestellar-demo-env.sh [hunk 2]
```diff
@@ -188,6 +188,16 @@ for image in "${images[@]}"; do
 done
 wait
 
+echo -e "\nFlatten images to single architecture to fix problems with kind load commands in recent Docker versions..."
+DOCKER_EMPTY_CONTEXT="$(mktemp -d)"
+trap 'rm -rf "$DOCKER_EMPTY_CONTEXT"' EXIT # Ensure it gets removed on script exit
```
[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply scripts/create-kubestellar-demo-env.sh]: This is a legitimate complaint.
I think that the simplest solution is to create both directories in adjacent commands and follow that with one trap that causes removal of both directories.

File: scripts/create-kubestellar-demo-env.sh [hunk 3]
```diff
@@ -188,6 +188,16 @@ for image in "${images[@]}"; do
...
+for image in "${images[@]}"; do
+    echo "FROM $image" | docker build -t "$image" -f- "$DOCKER_EMPTY_CONTEXT" &
```
[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply scripts/create-kubestellar-demo-env.sh]: This is a legitimate complaint.
I recommend directing each build commands stdout & stderr to a file and the `cat`ting those files sequentially after the builds are over.

Comment (MikeSpreitzer) [inline scripts/create-kubestellar-demo-env.sh]: Also, this will attempt to flatten an image that is already flat. Seems like overkill, but I do not know a quick and easy way to rule out the need for flattening, considering that problems come both from mult-platform and from the presence of an SBOM.

Comment (MikeSpreitzer) [inline scripts/create-kubestellar-demo-env.sh]: I am getting really strange results when testing this on my Apple Silicon Mac (whose ISA is arm64 v8), using `kind`. The image flatten part has lots of output, and buried in there is the following.

```
 1 warning found (use docker --debug to expand):
 - InvalidBaseImagePlatform: Base image quay.io/open-cluster-management/registration-operator:v0.15.2 was pulled with platform "linux/amd64", expected "linux/arm64" for current build (line 1)
```

Later when I `docker exec` into the kubeflex-control-plane container, note that all the OCM images are amd64.

```console
root@kubeflex-control-plane:/# crictl images | grep -v IMAGE | while read name tag id rest; do echo "$name:$tag - $(crictl inspecti  -o go-template --template='{{ .info.imageSpec.architecture }}' $id)"; done
docker.io/coredns/coredns:1.10.1 - arm64
registry.k8s.io/ingress-nginx/kube-webhook-certgen:<none> - arm64
docker.io/kindest/kindnetd:v20250214-acbabc1a - arm64
docker.io/kindest/local-path-helper:v20241212-8ac705d0 - arm64
docker.io/kindest/local-path-provisioner:v20250214-acbabc1a - arm64
docker.io/rancher/k3s:v1.27.2-k3s1 - arm64
docker.io/rancher/kine:v0.11.4 - arm64
ghcr.io/kubestellar/kubeflex/cmupdate:latest - arm64
ghcr.io/kubestellar/kubeflex/manager:0.9.1 - arm64
ghcr.io/kubestellar/kubestellar/controller-manager:0.29.0 - arm64
ghcr.io/kubestellar/kubestellar/ocm-transport-controller:0.29.0 - arm64
ghcr.io/kubestellar/ocm-status-addon:0.2.0-rc16 - arm64
ghcr.io/loft-sh/vcluster:0.16.4 - arm64
quay.io/brancz/kube-rbac-proxy:v0.19.1 - arm64
quay.io/kubestellar/clusteradm:0.10.1 - arm64
quay.io/kubestellar/helm:3.16.4 - arm64
quay.io/kubestellar/kubectl:1.29.3 - arm64
quay.io/kubestellar/kubectl:1.30.12 - arm64
quay.io/kubestellar/kubectl:1.30.14 - arm64
registry.k8s.io/ingress-nginx/controller:<none> - arm64
quay.io/kubestellar/postgresql:16.0.0-debian-11-r13 - arm64
quay.io/open-cluster-management/addon-manager:v0.15.2 - amd64
quay.io/open-cluster-management/placement:v0.15.2 - amd64
quay.io/open-cluster-management/registration-operator:v0.15.2 - amd64
quay.io/open-cluster-management/registration:v0.15.2 - amd64
quay.io/open-cluster-management/work:v0.15.2 - amd64
registry.k8s.io/coredns/coredns:v1.11.3 - arm64
registry.k8s.io/etcd:3.5.16-0 - arm64
registry.k8s.io/kube-apiserver-arm64:v1.32.2 - arm64
registry.k8s.io/kube-apiserver:v1.32.2 - arm64
registry.k8s.io/kube-apiserver:v1.29.9 - arm64
registry.k8s.io/kube-controller-manager-arm64:v1.32.2 - arm64
registry.k8s.io/kube-controller-manager:v1.32.2 - arm64
registry.k8s.io/kube-controller-manager:v1.29.9 - arm64
registry.k8s.io/kube-proxy-arm64:v1.32.2 - arm64
registry.k8s.io/kube-proxy:v1.32.2 - arm64
registry.k8s.io/kube-scheduler-arm64:v1.32.2 - arm64
registry.k8s.io/kube-scheduler:v1.32.2 - arm64
registry.k8s.io/pause:3.10 - arm64
```

Comment (MikeSpreitzer) [reply scripts/create-kubestellar-demo-env.sh]: I suspect that the v0.15.X multi-platform images of quay.io/open-cluster-management/registration-operator are broken.

The following shows that the multi-platform image has two ISAs.

```console
me@mymac kubestellar % oras manifest fetch quay.io/open-cluster-management/registration-operator:v0.15.2 
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 741,
         "digest": "sha256:3495f74d8873b872c2e27673c38fafd646f9d5977eabe9a64e36800331e33a44",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 741,
         "digest": "sha256:56b7ac0955851090b5d5359b1fe8b29ac9c6977ccba9e531a20d7422aed80527",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

But the one alleged to be arm64 is not!

```console
me@mymac kubestellar % oras manifest fetch-config quay.io/open-cluster-management/registration-operator@sha256:56b7ac0955851090b5d5359b1fe8b29ac9c6977ccba9e531a20d7422aed80527 | jq .
{
  "architecture": "amd64",
...
```

Comment (MikeSpreitzer) [reply scripts/create-kubestellar-demo-env.sh]: Oops, no, it's worse than that. It is not visible in the diff here, but the flattening is preceded by an unconditional `docker pull` --- which undoes the flattening!

Comment (MikeSpreitzer) [reply scripts/create-kubestellar-demo-env.sh]: (A) I suggest replacing the unconditional `docker pull` with a conditional one. Something like `if ! docker inspect $image &> /dev/null; then docker pull $image; fi`

(B) Since the image pulling is completed before the flattening starts, maybe do the flattening serially? That would avoid the troubles of parallel logging and failure handling (noted elsewhere in reviews of this PR).

File: Makefile [hunk 4]
```diff
@@ -212,9 +212,14 @@ ko-build-get-kubeconfig-local: ## Build local kflex-get-kubeconfig container ima
...
-	kind load --name ${KIND_HOSTING_CLUSTER} docker-image ${TRANSPORT_IMAGE}
-	kind load --name ${KIND_HOSTING_CLUSTER} docker-image ${GET_KFCFG_IMAGE}
+    DOCKER_EMPTY_CONTEXT := $(shell mktemp -d)
+    docker build -t "${CONTROLLER_MANAGER_IMAGE}" f- "$(DOCKER_EMPTY_CONTEXT)" <<< "FROM ${CONTROLLER_MANAGER_IMAGE}"
+    docker build -t "${TRANSPORT_IMAGE}" -f- "$(DOCKER_EMPTY_CONTEXT)" <<< "FROM ${TRANSPORT_IMAGE}"
+    docker build -t "${GET_KFCFG_IMAGE}" -f- "$(DOCKER_EMPTY_CONTEXT)" <<< "FROM ${GET_KFCFG_IMAGE}"
+    rm -rf "$(DOCKER_EMPTY_CONTEXT)"
+    kind load --name ${KIND_HOSTING_CLUSTER} docker-image ${CONTROLLER_MANAGER_IMAGE}
+    kind load --name ${KIND_HOSTING_CLUSTER} docker-image ${TRANSPORT_IMAGE}
+    kind load --name ${KIND_HOSTING_CLUSTER} docker-image ${GET_KFCFG_IMAGE}
```
Comment (MikeSpreitzer) [inline Makefile]: This change is not needed, because these images are single-platform images built by `ko` according to other recipes in this Makefile.

File: Makefile [hunk 5]
```diff
@@ -212,9 +212,14 @@ ko-build-get-kubeconfig-local: ## Build local kflex-get-kubeconfig container ima
 # this is used for local testing
 .PHONY: kind-load-image
 kind-load-image: ko-build-controller-manager-local ko-build-transport-local ko-build-get-kubeconfig-local
-	kind load --name ${KIND_HOSTING_CLUSTER} docker-image ${CONTROLLER_MANAGER_IMAGE}
-	kind load --name ${KIND_HOSTING_CLUSTER} docker-image ${TRANSPORT_IMAGE}
-	kind load --name ${KIND_HOSTING_CLUSTER} docker-image ${GET_KFCFG_IMAGE}
+    DOCKER_EMPTY_CONTEXT := $(shell mktemp -d)
+    docker build -t "${CONTROLLER_MANAGER_IMAGE}" f- "$(DOCKER_EMPTY_CONTEXT)" <<< "FROM ${CONTROLLER_MANAGER_IMAGE}"
```
Comment (MikeSpreitzer) [inline Makefile]: Missing dash (`-`) before the `f` flag here.
But this is moot because we do not need flattening in this Makefile recipe that loads locally-built single-platform images.

**Comment by MikeSpreitzer** [comment]
@francostellari: I have a few problems with the unconditional `docker pull` commands.

1. They certainly undo the flattening that was done by the previous run of either of the scripts.
2. Factoring the flattening out into a distinct earlier stage makes the scripting more complex. It would be simpler if there were no prefetch stage, just some builds in parallel.
3. I do not even know whether the `docker pull` helps the building at all. I keep reading about a "build cache".

**Comment by MikeSpreitzer** [comment]
I did some experimenting.

I found that the `docker pull` does NOT undo the flattening work from a previous run --- assuming (and I expect this will be the normal case) that the build cache was not cleared in between. The `FROM $image` statement gets a hit in the build cache. However, the `docker pull` does still do unnecessary work in second and subsequent runs of the script, re-fetching the top-level manifest from the origin registry and re-putting it in the local image store (NOT the build cache).

Also, it appears that the legacy builder can get images from docker's local image store. Doing `docker pull` of an image before the builder needs it means that the builder will not do its own pull. BTW, when the builder DOES have to do a pull, the pulled image does NOT go into the regular local image store.

Thus: of the three concerns that I enumerated in my previous comment:

1. Needs to be modified. The previous flattening work is NOT undone. However, there is unnecessary work done to re-establish content in the local image store.
2. This concern (script complexity) stands.
3. This concern has been discharged.

File: scripts/create-kind-cluster-with-SSL-passthrough.sh [hunk 6]
```diff
@@ -122,6 +122,8 @@ fi
 # Waiting for prefetching to complete... load images into cluster
```
Comment (MikeSpreitzer) [inline scripts/create-kind-cluster-with-SSL-passthrough.sh]: This comment becomes outdated. Perhaps something like the following?

> Wait for image prefetch, then flatten, then load into cluster.

**Review by MikeSpreitzer — COMMENTED** [review]
I think that the only show-stopper here is the buggy and unneeded mod to the Makefile.

I think that the scripting could be improved by getting rid of the `docker pull` commands and just doing parallel `docker build` commands. (As long as the `docker pull` commands are there, the `docker build` commands might as well be serialized --- it makes the script and output simpler and is unconditionally fast.)

**Comment by MikeSpreitzer** [comment]
FYI, the OCM multi-platform container images prior to v1.1.2 are all broken in this way: for ARM they point to an image that is actually for x86. OCM v1.1.2 uses too advanced a version Kubernetes for KubeStellar to use. So every flattening will produce a warning message as a consequence of the above breakage (and the warning message makes it look like an operator error rather than a problem in the original "image").

**Comment by MikeSpreitzer** [comment]
FYI, I did a study of what Claude code would do when asked to address the same problem. It found this PR, when Franco's branch pointed to commit 2296fdd36c1a440844a7910e3b6954ba960c17f5 (which it still does, as of this writing). To preserve that from GitHub GC, I pushed it to a branch in my own fork: https://github.com/MikeSpreitzer/kcp-edge-mc/tree/studied-fix-kind-load

File: scripts/create-kind-cluster-with-SSL-passthrough.sh (hunk 6 above)
Comment (francostellari) [reply scripts/create-kind-cluster-with-SSL-passthrough.sh]: Fixed in new commit

File: scripts/create-kubestellar-demo-env.sh (hunk 3 above)
[the remark this answers is not in the document]
Comment (francostellari) [reply scripts/create-kubestellar-demo-env.sh]: removed background processing

Comment (francostellari) [reply scripts/create-kubestellar-demo-env.sh]: Implemented the suggested check

File: scripts/create-kubestellar-demo-env.sh [hunk 7]
```diff
@@ -188,6 +188,16 @@ for image in "${images[@]}"; do
...
+    # NOTE that this simpler solution does not work because it strips ENTRYPOINT
+    # docker save "$image" | docker image import - "$image" &
+done
+wait
```
[the remark this answers is not in the document]
Comment (francostellari) [reply scripts/create-kubestellar-demo-env.sh]: done

[the remark this answers is not in the document]
Comment (francostellari) [reply scripts/create-kubestellar-demo-env.sh]: no more

File: scripts/create-kubestellar-demo-env.sh [hunk 8]
```diff
@@ -184,10 +184,24 @@ images=("ghcr.io/loft-sh/vcluster:0.16.4"
         "quay.io/kubestellar/postgresql:16.0.0-debian-11-r13")
 
 for image in "${images[@]}"; do
-    docker pull "$image" &
+    if ! docker inspect $image &> /dev/null; then
+        docker pull $image
```
Comment (MikeSpreitzer) [inline scripts/create-kubestellar-demo-env.sh:188]: Note that the `&` got dropped, so these are no longer being done in parallel.

**Comment by MikeSpreitzer** [comment]
The work on #3701 seems to have prodded the license checker into action.
