### PR TITLE
✨  Various improvements mainly wrt GitHub Actions workflows

### LINKED ISSUE #3017: bug: Permissions botches in website workflows
### Describe the bug

Attempts to use https://github.com/kubestellar/kubestellar/blob/main/.github/workflows/docs-gen-and-push.yml now fail.

An example is https://github.com/MikeSpreitzer/kcp-edge-mc/actions/runs/15992299097/workflow , which shows this complaint:

> The workflow is not valid. .github/workflows/docs-gen-and-push.yml (Line: 61, Col: 3): Error calling workflow 'MikeSpreitzer/kcp-edge-mc/.github/workflows/broken-links-crawler.yml@044a2b19645591b974ec3aedf5c9a8d43eb69f43'. The nested job 'broken-links-crawler' is requesting 'contents: write', but is only allowed 'contents: read'.

### Output from KubeStellar-Snapshot.sh

N/A

### Steps To Reproduce

Try to invoke the website rendering job on PR #3010 or anything later.

### Expected Behavior

Successful website rendering

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR makes a few related changes centered around the checking of the versions of the GitHub Actions referenced by workflows.

- Add an operation to the `hack/gha-reversemap.sh` script to do a full check of the intended discipline.
- Generalized that script to also process workflows whose filename ends with `.yaml` (since those are allowed too).
- Updated `.github/workflows/verify-action-hashes.yaml` to use the new check and to run on relevant PR events too.
- Fixed a violation uncovered by the new check.
- Updated the contributing guidlines to describe the intended discipline.
- Updated some outdated information in the same document.
- Added a list of good practices for PRs, addressing problems that have been seeing.
- Fixed two botches in workflow permissions introduced in #3010 .

Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-better-verify-actions/contribution-guidelines/contributing-inc/#pull-requests

## Related issue(s)

Fixes #3017

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
/cc @KPRoche 
/cc @clubanderson 
@rxinui 
@antedotee

File: hack/gha-reversemap.sh [hunk 1]
```diff
@@ -184,6 +189,40 @@ _get_sha_from_reversemap() {
...
+                _loginfo "$file uses $ref, and the reversemap has no entry for $action"
+                failed=true
+            elif ! [ "$version" == "$goodsha" ]; then
+                _loginfo "$file uses $ref, whose version $version is not the right one ($goodsha)"
+                failed=true
+            fi
+        done
+    done
+    if [ "$failed" == true ]; then
+        _exit_with_error $ERR_VERIFY_FAIL "Action reference problems found; see https://docs.kubestellar.io/unreleased-development/contribution-guidelines/contributing-inc/#github-action-reference-discipline"
```
Comment (MikeSpreitzer) [inline hack/gha-reversemap.sh:221]: The referenced fragment will exist after this PR merges.

File: CONTRIBUTING.md [hunk 2]
```diff
@@ -89,10 +99,32 @@ _Note: The GitHub web interface will assist you with adding the character; while
...
+repo](https://github.com/kubestellar/infra/) defines the Prow instance
+used for KubeStellar. The GitHub Actions workflows are found in [the
+.github/workflows
+directory](https://github.com/kubestellar/kubestellar/tree/main/.github/workflows).
+
+##### GitHub Action reference discipline
+
+For the sake of supply chain security, every reference from a workflow
+to an action identifies the action's version by a commit hash. In
+particular, there [a
```
Comment (pdettori) [inline CONTRIBUTING.md]: do you mean "there is [a file" ?

**Comment by MikeSpreitzer** [comment]
The force-push to c12a276db fixes the typo noted above.

File: CONTRIBUTING.md (hunk 2 above)
Comment (MikeSpreitzer) [reply CONTRIBUTING.md]: Yes. Fixed.
