### PR TITLE
✨ Handle CRDs at scale

### LINKED ISSUE #1705: bug:  client-side throttling when starting dynamic informers for (many) new CRDs
### Describe the bug

When starting of dynamic informers for new CRDs is enabled, in an OpenShift cluster which has ~ 280 CRDs installed, the kubestellar controller manager shows many `client-side throttling` messages in the log.

```
I0205 02:01:39.499569       1 request.go:697] Waited for 17.144362886s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/kubeflow.org/v1alpha1
I0205 02:01:49.499937       1 request.go:697] Waited for 27.144577753s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/operator.tigera.io/v1
2024-02-05T02:01:53Z    INFO    Placement       Got object event        {"apiextensions.k8s.io/v1": "CustomResourceDefinition", "": "trustyaiservices.trustyai.opendatahub.io.trustyai.opendatahub.io"}
I0205 02:01:59.700193       1 request.go:697] Waited for 37.343447865s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/authorization.openshift.io/v1
I0205 02:02:09.899934       1 request.go:697] Waited for 47.543101288s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/observability.open-cluster-management.io/v1beta2
I0205 02:02:20.099804       1 request.go:697] Waited for 57.742738621s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/workload.codeflare.dev/v1beta1
I0205 02:02:30.100048       1 request.go:697] Waited for 8.794602429s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/packages.operators.coreos.com/v1
I0205 02:02:40.100055       1 request.go:697] Waited for 18.794475039s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/apiserver.openshift.io/v1
I0205 02:02:50.300102       1 request.go:697] Waited for 28.994482276s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/tekton.dev/v1
I0205 02:03:00.499286       1 request.go:697] Waited for 38.993577734s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/mcad.ibm.com/v1beta1
I0205 02:03:10.499820       1 request.go:697] Waited for 48.993988956s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/policy.open-cluster-management.io/v1
I0205 02:03:20.700052       1 request.go:697] Waited for 59.193708821s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/hive.openshift.io/v1
I0205 02:03:30.899001       1 request.go:697] Waited for 1m9.19315794s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/imageregistry.operator.openshift.io/v1
I0205 02:03:40.899537       1 request.go:697] Waited for 1m19.193581633s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/lighthouse.submariner.io/v2alpha1
I0205 02:03:50.899980       1 request.go:697] Waited for 1m28.994554135s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/certificates.k8s.io/v1
I0205 02:04:01.099382       1 request.go:697] Waited for 1m39.19373169s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/flowcontrol.apiserver.k8s.io/v1beta3
I0205 02:04:11.099508       1 request.go:697] Waited for 1m49.193740238s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/addon.open-cluster-management.io/v1alpha1
I0205 02:04:22.499022       1 request.go:697] Waited for 1.19403917s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/networking.k8s.io/v1
I0205 02:04:32.499979       1 request.go:697] Waited for 11.194659797s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/oauth.openshift.io/v1
2024-02-05T02:04:33Z    INFO    Placement       Got object event        {"apiextensions.k8s.io/v1": "CustomResourceDefinition", "": "predictors.serving.kserve.io"}
I0205 02:04:42.499920       1 request.go:697] Waited for 21.194715153s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/submariner.io/v1alpha1
I0205 02:04:52.698761       1 request.go:697] Waited for 31.193879603s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/events.k8s.io/v1
I0205 02:05:02.699252       1 request.go:697] Waited for 41.194219885s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/operators.coreos.com/v1alpha2
I0205 02:05:12.699427       1 request.go:697] Waited for 51.194329866s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/tekton.dev/v1
2024-02-05T02:05:17Z    INFO    Placement       Got object event        {"apiextensions.k8s.io/v1": "CustomResourceDefinition", "": "datasciencepipelinesapplications.datasciencepipelinesapplications.opendatahub.io"}
I0205 02:05:22.898830       1 request.go:697] Waited for 1m1.192828889s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/autoscaling/v1
I0205 02:05:32.898933       1 request.go:697] Waited for 1m11.192823041s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/crd.projectcalico.org/v1
2024-02-05T02:05:37Z    INFO    Placement       Got object event        {"apiextensions.k8s.io/v1": "CustomResourceDefinition", "": "trustyaiservices.trustyai.opendatahub.io.trustyai.opendatahub.io"}
I0205 02:05:42.899554       1 request.go:697] Waited for 1m21.19331421s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/operators.coreos.com/v1
I0205 02:05:53.099467       1 request.go:697] Waited for 1m31.194016075s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/autoscaling/v2
I0205 02:06:03.299339       1 request.go:697] Waited for 1m41.393774303s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/kubeflow.org/v1alpha1
I0205 02:06:13.499646       1 request.go:697] Waited for 1m51.594011096s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/multicluster.x-k8s.io/v1alpha1
I0205 02:06:23.699689       1 request.go:697] Waited for 2.395233485s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/proxy.open-cluster-management.io/v1beta1
I0205 02:06:33.898757       1 request.go:697] Waited for 12.594184958s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.default.svc/apis/edge.kubestellar.io/v1alpha1
```

### Steps To Reproduce

1. Run the KS controller in a cluster with a large number of CRDs and observe the log

### Expected Behavior

There should not be client-side throttling 

### Additional Context

It is most likely that client-side throttling is due to inefficiency of the code for detecting new api resources and starting the related informers. For each new CRD, the CRD handler invokes the dynamic client's ServerPreferredResources(), which lists all preferred API resources on the API server. At controller startup, this call happens for each CRD resource present on the cluster (which can be hundreds) and as a result that causes the client-side throttling.

https://github.com/kubestellar/kubestellar/blob/04fc0d219561582c2787f0b85fb29b6909282d70/pkg/placement/crd.go#L83

The code could be improved by just getting the new CRD from the CRD lister, finding the GVR for the resource and starting the informer for that GVR, rather than calling ServerPreferredResources for every new CRD.

### PR DESCRIPTION
**Pull request by waltforme**
## Summary
Large number of CRDs (e.g. in an OpenShift cluster) may cause issues like #1705 . This PR makes several changes to handle large number or CRDs.

### What's done in this PR
Three things are done in this PR:
1. Change the way that the binding controller handles CRD objects. Previously, for each CRD object, the controller computes the symmetric difference of existing resources and watched resources, in a holistic manner. That requires repeated requests to apiserver for discovery. With this change, the controller focuses on the CRD object only, in a incremental manner, which saves the requests to the apiserver and is more efficient.
2. Make the client-side rate limiter adaptive to: the number of GVRs in the apiserver when the binding controller starts. Together with 1, the client-side throttling is eliminated (see the 'Result' section below for details).
3. Write tests for the binding controller to test the changed behavior.

### Result
Before the change, I can observe the client-side throttling at the start of the binding controller.
- For a cluster which supports aggregated discovery, the throttling is primarily triggered when the reflectors are doing list and watch.
- For a cluster which doesn't support aggregated discovery, additional throttling (also longer waits) is trigger by the initial, intensive, reconciliation cycles for CRD objects.
```
I0228 14:55:43.122143  761795 request.go:629] Waited for 8.152398561s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/synthetic-crd.com/v1alpha1/cr11s?limit=500&resourceVersion=0
I0228 14:55:43.322485  761795 request.go:629] Waited for 8.352711234s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/synthetic-crd.com/v1alpha1/cr30s?limit=500&resourceVersion=0
I0228 14:55:43.522831  761795 request.go:629] Waited for 8.552861282s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/synthetic-crd.com/v1alpha1/cr72s?limit=500&resourceVersion=0
I0228 14:55:43.522865  761795 request.go:697] Waited for 8.552861282s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/synthetic-crd.com/v1alpha1/cr72s?limit=500&resourceVersion=0
I0228 14:55:43.722340  761795 request.go:629] Waited for 8.752317832s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/synthetic-crd.com/v1alpha1/cr25s?limit=500&resourceVersion=0
I0228 14:55:43.922619  761795 request.go:629] Waited for 8.952537192s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/synthetic-crd.com/v1alpha1/cr65s?limit=500&resourceVersion=0
I0228 14:55:44.122122  761795 request.go:629] Waited for 9.152017818s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/synthetic-crd.com/v1alpha1/cr21s?limit=500&resourceVersion=0
I0228 14:55:44.322700  761795 request.go:629] Waited for 9.352440908s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/synthetic-crd.com/v1alpha1/cr67s?limit=500&resourceVersion=0
I0228 14:55:44.521954  761795 request.go:629] Waited for 9.551632207s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/synthetic-crd.com/v1alpha1/cr39s?limit=500&resourceVersion=0
I0228 14:55:44.722205  761795 request.go:629] Waited for 9.750876057s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/synthetic-crd.com/v1alpha1/cr73s?limit=500&resourceVersion=0
I0228 14:55:44.722233  761795 request.go:697] Waited for 9.750876057s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/synthetic-crd.com/v1alpha1/cr73s?limit=500&resourceVersion=0
I0228 14:55:44.922686  761795 request.go:629] Waited for 9.951253423s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/synthetic-crd.com/v1alpha1/cr44s?limit=500&resourceVersion=0
I0228 14:55:45.122104  761795 request.go:629] Waited for 10.150663768s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/synthetic-crd.com/v1alpha1/cr76s?limit=500&resourceVersion=0
```
I synthesized the CRDs in group `synthetic-crd.com` above. I populated roughly 100 CRDs into the WDS.

After the changes, the client-side throttling is gone.

Closes #1705

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
With this change, does the controller-manager succeed without `--api-groups` when an OpenShift cluster is playing the WDS role?

File: pkg/binding/controller.go [hunk 1]
```diff
@@ -99,17 +99,27 @@ type Controller struct {
...
 	}
 
-	kubernetesClient, err := kubernetes.NewForConfig(wdsRestConfig)
+	extClient, err := apiextensionsclientset.NewForConfig(wdsRestConfig)
 	if err != nil {
 		return nil, err
 	}
 
-	extClient, err := apiextensionsclientset.NewForConfig(wdsRestConfig)
+	burst, err := countGVRsViaAggregatedDiscovery(rest.CopyConfig(wdsRestConfig)) // use # of GVRs as burst is tested to be working well
```
Comment (MikeSpreitzer) [inline pkg/binding/controller.go:112]: We could pass `kubernetesClient` here instead of `wdsRestConfig`, right? Passing the client would save a bit of source code and runtime cost; most importantly, it would make the counting func more easily testable.

File: pkg/binding/crd.go [hunk 2]
```diff
@@ -35,19 +37,43 @@ type APIResource struct {
...
+	uObj := obj.(*unstructured.Unstructured)
+	var crdObj *apiextensionsv1.CustomResourceDefinition
+	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(uObj.UnstructuredContent(), &crdObj); err != nil {
+		return fmt.Errorf("failed to convert Unstructured to CRD: %w", err)
+	}
+
+	toStart := APIResource{
+		groupVersion: schema.GroupVersion{
+			Group:   crdObj.Spec.Group,
+			Version: crdObj.Spec.Versions[0].Name,
```
Comment (MikeSpreitzer) [inline pkg/binding/crd.go:50]: I wonder if it is safe to look at `[0]` and no other. I thought that `v1` and `v2` have distinct populations of objects. Also, I looked at https://github.com/kubernetes/apiextensions-apiserver/blob/v0.28.2/pkg/apis/apiextensions/v1/types.go ; could `[0]` have `Served==false`?

**Comment by MikeSpreitzer** [comment]
Did you consider using https://github.com/kubernetes/client-go/blob/v0.28.2/discovery/cached/memory/memcache.go#L326 with invalidation on create/update/delete of a CRD?

**Comment by ezrasilvera** [comment]
@waltforme Thanks for the PR.  I'm curious do you know which change made the main impact ? E.g., If we would have just changed the client-side rate limiter would that solve the issue without the other changes?

**Comment by ezrasilvera** [comment]
@waltforme Does this suppose to fix #1705 ?  If so can you please add `Fixes`  statement so they are linked .

**Comment by waltforme** [comment]
Force-push to https://github.com/kubestellar/kubestellar/pull/1828/commits/c1aa6c0bc2656c2209108008cecb00243ed7dd73 includes some changes in response to comments, squashing the changes into appropriate commits, and rebasing on main.

**Comment by waltforme** [comment]
> With this change, does the controller-manager succeed without `--api-groups` when an OpenShift cluster is playing the WDS role?

I wish I could.

At the beginning of this work, I tried to run the controller against an OpenShift cluster. But I got 
```
Get "https://imbs1-imbs1-system.edgeplatform1-9ca4d14d48413d18ce61b80811ba4308-0000.us-south.containers.appdomain.cloud:443/api": dial tcp 169.61.129.125:443: i/o timeout
```
I guess I was missing some ingress/route, so I tried [Create an nginx Ingress controller with SSL passthrough](https://raw.githubusercontent.com/kubestellar/kubestellar/main/example/kind-nginx-ingress-with-SSL-passthrough.yaml), which doesn't seem to work out-of-box.

I saw the log in #1705 is from some OpenShift cluster. So @pdettori Would you share how did you run the controller against an OpenShift cluster? Ideally not as a pod, but as a bare process so that weI can debug and make changes efficiently.

File: pkg/binding/controller.go [hunk 3]
```diff
@@ -99,17 +99,27 @@ type Controller struct {
...
+	if err != nil {
+		parentLogger.Error(err, "Not able to count GVRs via aggregated discovery") // but we can still continue
+	}
+	wdsRestConfig.Burst = adjustBurstIfNecessary(burst)
+	wdsRestConfig.QPS = adjustQPSIfNecessary(float32(burst) / 4)
```
[the remark this answers is not in the document]
Comment (waltforme) [reply pkg/binding/controller.go]: I rewrote this section of code, and renamed the functions. Does it look better now? BTW what is the exact 'side-effect' you mentioned above?

File: pkg/binding/controller.go (hunk 1 above)
Comment (waltforme) [reply pkg/binding/controller.go]: Good point. Changed as suggested.

File: pkg/binding/crd.go (hunk 2 above)
Comment (waltforme) [reply pkg/binding/crd.go]: Added in https://github.com/kubestellar/kubestellar/pull/1828/commits/c1aa6c0bc2656c2209108008cecb00243ed7dd73 the functionality to manage the watches of multiple versions of a CRD.

**Comment by waltforme** [comment]
> @waltforme Thanks for the PR. I'm curious do you know which change made the main impact ? E.g., If we would have just changed the client-side rate limiter would that solve the issue without the other changes?

Yes, I would say primarily adapting the relate limiter solved the problem.

Before the current changes in this PR, I can observe two bursts of requests, both at the start of the controller, and both may trigger the client-side throttling.
Burst 1: Requests from the reflectors' ListAndWatch, with longer 'Waited for' time.
Burst 2. Requests from `handleCRD` during the initial intensive reconciliation cycles of CRD objects, with shorter 'Waited for' time than Burst 1. These requests trigger client-side throttling *only* if I intentionally set the limit of the rate to some low values in my experiments.

So primarily, adapting the relate limiter solved the problem. But another change (change the handling to an incremental manner), actually eliminates *any* requests from `handleCRD` during the reconciliation cycles, thus eradicates the possibility of throttling due to Burst 2.

P.S. Yes, it will fix #1705 so I linked to it.

**Comment by waltforme** [comment]
> Did you consider using https://github.com/kubernetes/client-go/blob/v0.28.2/discovery/cached/memory/memcache.go#L326 with invalidation on create/update/delete of a CRD?

I did. Because I saw the [discussions](https://github.com/kubestellar/kubestellar/issues/1705#issuecomment-1927490445) in #1705. But I realized that using a cached discovery client may not help us.

With the cached discovery client, we still need to make requests to the apiserver from time to time during the reconciliation cycles --- as you mentioned, on create/update/delete of a CRD. That will be not much different from the behavior before the changes in this PR.

OTOH, the changes in this PR eliminates any requests from handleCRD during the reconciliation cycles. (I put more details regarding 'Burst 2' in [the comment above](https://github.com/kubestellar/kubestellar/pull/1828#issuecomment-1971722249).)

**Comment by ezrasilvera** [comment]
@waltforme Thanks.  From my side it's  LGTM .  I'll let @MikeSpreitzer put the official lgtm label.

**Comment by pdettori** [comment]
> Would you share how did you run the controller against an OpenShift cluster? 

@waltforme - I was able to run on an existing OCP cluster from my local desktop by scaling down the KS controller to 0 replicas and then using `make run` with the kubeconfig context set to the kubeconfig of the hosting cluster. The controller connects to the hosting cluster and uses the CPs to get the secrets with the kubeconfigs (it should use the external kubeconfig and then connects). In your case the issue seems that your controller does not communicate with the imbs API server. Did you have your VPN to IBM Cloud connected during the test ?

**Review by pdettori — COMMENTED** [review]
/lgtm 
Thanks @waltforme ! will wait for @MikeSpreitzer to see if has more comments on his side before doing an approve

**Comment by waltforme** [comment]
@pdettori Thanks! This is really helpful.

> @waltforme - I was able to run on an existing OCP cluster from my local desktop by scaling down the KS controller to 0 replicas and then using `make run` with the kubeconfig context set to the kubeconfig of the hosting cluster. The controller connects to the hosting cluster and uses the CPs to get the secrets with the kubeconfigs (it should use the external kubeconfig and then connects). In your case the issue seems that your controller does not communicate with the imbs API server. Did you have your VPN to IBM Cloud connected during the test ?

**Comment by waltforme** [comment]
I ran the controller against an OpenShift cluster (i.e. let the OpenShift cluster serve as a KubeFlex ControlPlane of type `host`, and apply `kflex.kubestellar.io/cptype=wds` label to the ControlPlane). Then I collected logs of the binding controller, both before the changes in this PR and after the changes in this PR, as attached.

Before the changes, we can see a lot of throttling messages, and the controller starts very slowly, I quit in the middle so the log is incomplete.

After the changes, the controller starts in seconds.
[before_1828_too_long_incomplete.txt](https://github.com/kubestellar/kubestellar/files/14455861/before_1828_too_long_incomplete.txt)
[after_1828_complete.txt](https://github.com/kubestellar/kubestellar/files/14455862/after_1828_complete.txt)

**Comment by pdettori** [comment]
this looks great @waltforme - did you run with or without the --api-groups flag to select a subset of resources ?

File: pkg/util/resources.go [hunk 4]
```diff
@@ -39,8 +39,8 @@ func ParseAPIGroupsString(apiGroups string) sets.Set[string] {
 	return groupsSet
 }
 
-// IsResourceGroupAllowed checks if a API group is allowed
-// an empty or nil allowedResources slice is equivalent to allow all,
+// IsResourceGroupAllowed checks if a API group is explicitly allowed by user,
+// an empty or nil allowedResources slice is equivalent to allow all.
```
Comment (pdettori) [inline pkg/util/resources.go:43]: can you please re-enable  `allowedResourceGroups.Insert(apiextensions.GroupName)` as part of this PR? it was disabled exactly because of the throttling issue.

Comment (waltforme) [reply pkg/util/resources.go:44]: Done in https://github.com/kubestellar/kubestellar/pull/1828/commits/215a066fa16f731a4cfc6595239a5834cba6b0f3.

Comment (waltforme) [reply pkg/util/resources.go:43]: Reverted because re-enabling calls for some unit test cases to be updated. Will look at the test cases tmr.

File: pkg/binding/crd.go [hunk 5]
```diff
@@ -35,19 +37,50 @@ type APIResource struct {
...
+				Kind: crdObj.Spec.Names.Kind,
+			},
+		}
+		key := util.KeyForGroupVersionKind(gvr.groupVersion.Group, gvr.groupVersion.Version, gvr.resource.Kind)
+		if isBeingDeleted(obj) {
+			toStopList = append(toStopList, key)
+			continue
+		}
+		if !c.includedToWatch(gvr) {
+			toStopList = append(toStopList, key)
```
Comment (MikeSpreitzer) [inline pkg/binding/crd.go:66]: If `!c.includedToWatch(gvr)`, aren't we guaranteed that it has not been started? `c.includedToWatch` does not vary its behavior over time.

File: pkg/binding/crd.go [hunk 6]
```diff
@@ -35,19 +37,50 @@ type APIResource struct {
...
 
 	go c.startInformersForNewAPIResources(toStartList)
 
 	for _, key := range toStopList {
-		c.logger.Info("API removed, stopping informer.", "key", key)
-		stopper := c.stoppers[key]
-		// close channel
-		close(stopper)
+		c.logger.Info("API should be removed, stopping informer.", "key", key)
+		if stopper, ok := c.stoppers[key]; ok {
```
Comment (MikeSpreitzer) [inline pkg/binding/crd.go:80]: Why might `ok` be `false`? Is it only because of including things in `toStopList` that never pass `c.includedToWatch`?

File: pkg/binding/crd.go [hunk 7]
```diff
@@ -35,19 +37,50 @@ type APIResource struct {
...
 	}
 
 	go c.startInformersForNewAPIResources(toStartList)
 
 	for _, key := range toStopList {
-		c.logger.Info("API removed, stopping informer.", "key", key)
-		stopper := c.stoppers[key]
-		// close channel
-		close(stopper)
+		c.logger.Info("API should be removed, stopping informer.", "key", key)
```
Comment (MikeSpreitzer) [inline pkg/binding/crd.go:79]: FYI, I would let the log message carry the information from `ok` below.

File: pkg/binding/crd.go [hunk 8]
```diff
@@ -35,19 +37,50 @@ type APIResource struct {
...
+			continue
+		}
+		if !ver.Served {
+			toStopList = append(toStopList, key)
+			continue
+		}
+		toStartList = append(toStartList, gvr)
 	}
 
 	go c.startInformersForNewAPIResources(toStartList)
```
Comment (MikeSpreitzer) [inline pkg/binding/crd.go:76]: What if some members of `toStartList` are already being informed on?

File: pkg/util/resources.go (hunk 4 above)
Comment (MikeSpreitzer) [reply pkg/util/resources.go:43]: `controller_test.go` is junk, for the reason not clearly stated in https://github.com/kubestellar/kubestellar/pull/1775#issuecomment-1951422945 . The fakes do not support the sort of discovery that this controller uses, so the test can not exercise much. We should either delete this junk test or change it to use better fakes or change the controller to use the other kind of discovery.

Comment (MikeSpreitzer) [reply pkg/util/resources.go:43]: @pdettori : can you please elaborate on what you are asking to be re-enabled?

**Comment by MikeSpreitzer** [comment]
In the opening comment, in item 2, I would clarify that the rate limiter --- which is constructed just once at controller startup --- is sensitive to the number of GVRs reported by discovery _at the time of controller startup_.

File: test/integration/controller-manager/crd-handling_test.go [hunk 9]
```diff
@@ -0,0 +1,294 @@
...
+	k8sjson "k8s.io/apimachinery/pkg/runtime/serializer/json"
+	"k8s.io/apimachinery/pkg/util/wait"
+	"k8s.io/klog/v2/ktesting"
+	kastesting "k8s.io/kubernetes/cmd/kube-apiserver/app/testing"
+	"k8s.io/kubernetes/test/integration/framework"
+
+	"github.com/kubestellar/kubestellar/pkg/binding"
+)
+
+// An integration test for the binding controller.
```
Comment (MikeSpreitzer) [inline test/integration/controller-manager/crd-handling_test.go:37]: Integration tests should go in the `test/integration` directory.

File: pkg/binding/controller.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply pkg/binding/controller.go]: The side-effects are still there. I am talking about modifying the struct that the pointer parameter `wdsRestConfig` points to.

File: pkg/binding/crd.go [hunk 10]
```diff
@@ -35,19 +37,50 @@ type APIResource struct {
...
+		}
+		if !c.includedToWatch(gvr) {
+			toStopList = append(toStopList, key)
+			continue
+		}
+		if !ver.Served {
+			toStopList = append(toStopList, key)
+			continue
+		}
+		toStartList = append(toStartList, gvr)
```
Comment (MikeSpreitzer) [inline pkg/binding/crd.go:73]: Welcome to the world of CRD dynamics. Please review https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apis/apiextensions/v1/types.go#L308 before proceeding further.

File: pkg/binding/controller.go [hunk 11]
```diff
@@ -99,17 +100,28 @@ type Controller struct {
...
 
-	extClient, err := apiextensionsclientset.NewForConfig(wdsRestConfig)
+	nGVRs, err := countGVRsViaAggregatedDiscovery(kubernetesClient)
+	if err != nil {
+		parentLogger.Error(err, "Not able to count GVRs via aggregated discovery") // but we can still continue
+	}
+	// tuning the rate limiter based on the number of GVRs is tested to be working well
+	wdsRestConfig.Burst = computeBurstFromNumGVRs(nGVRs)
+	wdsRestConfig.QPS = computeQPSFromNumGVRs(nGVRs)
+	parentLogger.V(1).Info("Parameters of the client's token bucket rate limiter", "burst", wdsRestConfig.Burst, "qps", wdsRestConfig.QPS)
```
Comment (MikeSpreitzer) [inline pkg/binding/controller.go:120]: This logging should be done via the controller's logger rather than the parent logger.

File: pkg/binding/controller.go [hunk 12]
```diff
@@ -124,6 +136,50 @@ func NewController(parentLogger logr.Logger, wdsRestConfig *rest.Config, imbsRes
 	return makeController(parentLogger, dynamicClient, kubernetesClient, extClient, ocmClientset, ocmClient, wdsName, allowedGroupsSet)
 }
 
+func countGVRsViaAggregatedDiscovery(countClient kubernetes.Interface) (int, error) {
+	dc := countClient.Discovery().(*discovery.DiscoveryClient)
+	if dc.UseLegacyDiscovery { // by default it should be false already, just double check
+		dc.UseLegacyDiscovery = false
+	}
+	apiResourceLists, err := dc.ServerPreferredResources()
```
Comment (MikeSpreitzer) [inline pkg/binding/controller.go:144]: This can be expensive! Wouldn't it be better to find a way to do it only once?

File: pkg/binding/controller.go [hunk 13]
```diff
@@ -124,6 +136,50 @@ func NewController(parentLogger logr.Logger, wdsRestConfig *rest.Config, imbsRes
...
+	if err != nil {
+		return 0, fmt.Errorf("error listing server perferred resources: %w", err)
+	}
+	n := 0
+	for _, list := range apiResourceLists {
+		n += len(list.APIResources)
```
Comment (MikeSpreitzer) [inline pkg/binding/controller.go:150]: Why not apply `util.IsAPIGroupAllowed` here?

File: pkg/binding/crd.go [hunk 14]
```diff
@@ -35,19 +38,55 @@ type APIResource struct {
...
+	if len(toStartList) > 0 {
+		go c.startInformersForNewAPIResources(ctx, toStartList)
+	}
 
 	for _, key := range toStopList {
-		c.logger.Info("API removed, stopping informer.", "key", key)
-		stopper := c.stoppers[key]
-		// close channel
-		close(stopper)
+		logger.Info("API should not be watched, stopping informer.", "key", key)
```
Comment (MikeSpreitzer) [inline pkg/binding/crd.go:85]: This log message is misleading when `ok` in the next statement is `false`.

File: pkg/binding/controller.go (hunk 13 above)
Comment (MikeSpreitzer) [reply pkg/binding/controller.go:150]: Or `includedToWatch`

File: pkg/binding/crd.go [hunk 15]
```diff
@@ -58,69 +97,32 @@ func (c *Controller) handleCRD(_ runtime.Object) error {
...
+	return false
 }
 
-func (c *Controller) startInformersForNewAPIResources(toStartList []APIResource) {
+func (c *Controller) startInformersForNewAPIResources(ctx context.Context, toStartList []APIResource) {
+	logger := klog.FromContext(ctx)
 	for _, toStart := range toStartList {
-		c.logger.Info("New API added. Starting informer for:", "group", toStart.groupVersion.Group,
+		logger.Info("Ensuring informer for:", "group", toStart.groupVersion.Group,
 			"version", toStart.groupVersion, "kind", toStart.resource.Kind)
```
Comment (MikeSpreitzer) [inline pkg/binding/crd.go:127]: I see a lot of work below that could be conditional on whether `key` is already in `c.informers`.

File: pkg/util/resources.go (hunk 4 above)
Comment (MikeSpreitzer) [reply pkg/util/resources.go:44]: Now I see what @pdettori is talking about.

Comment (waltforme) [reply pkg/util/resources.go:44]: Redid in https://github.com/kubestellar/kubestellar/pull/1828/commits/185029311709dc9ececfac041a272c8009dd5c2d together updated unit tests.

File: pkg/binding/crd.go (hunk 5 above)
Comment (waltforme) [reply pkg/binding/crd.go:67]: Changed in latest push.

File: pkg/binding/crd.go (hunk 7 above)
Comment (waltforme) [reply pkg/binding/crd.go]: Added in latest push.

File: pkg/binding/controller.go (hunk 11 above)
Comment (waltforme) [reply pkg/binding/controller.go:120]: Controller, as the golang struct, doesn't have access to the values, right?

File: pkg/binding/controller.go (hunk 12 above)
Comment (waltforme) [reply pkg/binding/controller.go:144]: Not sure I understand the question. This PR is doing exactly reducing the number of calls to `ServerPreferredResources()` (during CRD handling) to only one. And the only one is right here.

File: pkg/binding/controller.go (hunk 13 above)
Comment (waltforme) [reply pkg/binding/controller.go:150]: I think the estimation doesn't have to be accurate. Actually we want to tune the limiter in favor of the performance. Also, the parameters of the limiter is bounded by `computeBurstFromNumGVRs` and `computeQPSFromNumGVRs` anyway.

File: pkg/binding/crd.go (hunk 14 above)
Comment (waltforme) [reply pkg/binding/crd.go]: Revised.

File: pkg/binding/crd.go (hunk 15 above)
Comment (waltforme) [reply pkg/binding/crd.go:129]: Done in latest push.

File: pkg/binding/controller.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (waltforme) [reply pkg/binding/controller.go]: Still not following. Which line modifies the struct `wdsRestConfig`, as a pointer parameter (or in other words as 'an input data structure')? I thought the modifications are explicit and not modifying as any input data structure in current lines 118 and 119.

File: pkg/binding/crd.go (hunk 7 above)
Comment (MikeSpreitzer) [reply pkg/binding/crd.go]: I do not see that change in https://github.com/kubestellar/kubestellar/blob/48f75f51b37bd325ad4c075aa15ad0c6b2158d6b/pkg/binding/crd.go#L84-L85

Comment (MikeSpreitzer) [reply pkg/binding/crd.go]: FYI: I was trying to suggest that there would be just one log message in both cases (`ok` and `!ok`), with the log messages somehow letting the reader know whether `ok` was true or not. For example, have two different log statements (in the two arms of the `if`), which would not need an additional log statement up front.

File: pkg/binding/controller.go (hunk 11 above)
Comment (MikeSpreitzer) [reply pkg/binding/controller.go:120]: I am not sure I understand. In the current version of this PR (https://github.com/kubestellar/kubestellar/blob/48f75f51b37bd325ad4c075aa15ad0c6b2158d6b/pkg/binding/controller.go), the controller does not even exist at the point in code that we are discussing. To use the controller's logger here would require moving the construction of that logger from inside `makeController` to somewhere earlier than the line we are discussing.

File: pkg/binding/controller.go (hunk 12 above)
Comment (MikeSpreitzer) [reply pkg/binding/controller.go:144]: I see that func also being called at https://github.com/kubestellar/kubestellar/blob/48f75f51b37bd325ad4c075aa15ad0c6b2158d6b/pkg/binding/controller.go#L249 and https://github.com/kubestellar/kubestellar/blob/48f75f51b37bd325ad4c075aa15ad0c6b2158d6b/pkg/crd/crds.go#L94

File: pkg/binding/crd.go (hunk 15 above)
Comment (MikeSpreitzer) [reply pkg/binding/crd.go:129]: I see the early-out now. I am surprised by the retention of the complex code later for updating `c.listers`, `c.informers`, and `c.stoppers`. Aren't they coordinated? For a given key, either all three have an entry or all three do not have an entry, right? BTW, this would be more clearly handled by one map from key to a pointer to a struct holding the informer, lister, and stopper.

File: pkg/binding/controller.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (waltforme) [reply pkg/binding/controller.go]: I finally see the point (it would have been helpful in the first comment to say the input data structure **of `NewController`**). But I do have a different view on this issue and would like to discuss as follows.

My view is that if a caller passes a pointer to a callee, the caller should be 'prepared' that the pointed content may be modified. If the caller doesn't want the possible modification, than pass a copy or value instead. In other words, if a pointer is passed, than permission of modification is implicit.

Is there some established convention (pls do let me know if there is)? Or this view can vary from person to person?

File: pkg/binding/controller.go (hunk 11 above)
Comment (waltforme) [reply pkg/binding/controller.go:120]: > the controller does not even exist at the point in code that we are discussing

This is exactly what made me confused. So what you suggested is to construct the controller's log earlier and use it. I get the point. But what is the issue of using the `parentLogger` instead? BTW why is it called `parentLogger`, i.e. who is the child?

Comment (MikeSpreitzer) [reply pkg/binding/controller.go:120]: The binding controller is just one of the controllers in the controller-manager process.

File: pkg/binding/controller.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply pkg/binding/controller.go]: I am not aware of a universal convention about this for programming in Go. However, we are talking here about a more specific subject matter: setting up controllers in Kubernetes code. The convention in Kubernetes code is that the consumer of a REST config does not side-effect the copy given unless there is something explicit in the func's name or comments about that. The consumer can make a copy for its own purpose, if necessary.

**Review by MikeSpreitzer — APPROVED** [review]
This is good enough to merge. The remaining issues can be addressed in follow-on.
/lgtm
/approve
Thanks!
